# Settings that the LAMMPS build will import when this package library is used
#
nufeb_SYSINC = -DENABLE_DUMP_BIO_HDF5 -I../../../thirdparty/hdf5-1.10.5/hdf5/include
nufeb_SYSLIB = -lhdf5 -L../../../thirdparty/hdf5-1.10.5/hdf5/lib
nufeb_SYSPATH = 
