
!	THIS SUB_MODEL SOLVE SUBSTRATE DISTRIBUTION AND MICROBIAL GROWTH
!	UNITS ARE: KG-->MASS, M-->LENGTH, DAY-->TIME
!   ONLY THE MICRO-SCALE COMPUTATIONAL DOMAIN IS INCLUDED; BIOREACTOR COUPLING IS OMITTED.

MODULE GLOBAL_VARIABLES  !DEFINE GLOBAL VARIABLES
IMPLICIT NONE
INTEGER,SAVE::MX,MY,MZ,ITER_GROWTH,N_GROWTH,MASS_TRANSFER  
REAL(8),SAVE::LX,LY,LZ,DX,DY,DZ,XMIN,XMAX,YMIN,YMAX,ZMIN,ZMAX,DT_BIO,DT_PHY,TIME_BIO,TIME_PHY,TOTAL_TIME_BIO, TOTAL_TIME_PHY
REAL(8),ALLOCATABLE,SAVE::XS(:),YS(:),ZS(:),UX(:,:,:),UY(:,:,:),UZ(:,:,:),S_O2(:,:,:),S_NO2(:,:,:),S_NO3(:,:,:),S_NH4(:,:,:),S_S(:,:,:),D_O2(:,:,:),D_NO2(:,:,:),D_NO3(:,:,:),D_NH4(:,:,:),D_S(:,:,:),R_S(:,:,:),R_O2(:,:,:),R_NH4(:,:,:),R_NO2(:,:,:),R_NO3(:,:,:)
REAL(8),ALLOCATABLE,SAVE::X_HET(:,:,:),X_AOB(:,:,:),X_NOB(:,:,:),X_EPS(:,:,:),X_I(:,:,:),X_S(:,:,:)
REAL(8),SAVE::MU_M_HET,MU_M_AOB,MU_M_NOB,B_HET,B_EPS,B_AOB,B_NOB,K_O2_HET,K_S_HET,K_NO2_HET,K_NO3_HET,K_O2_AOB,K_NH4_AOB,K_O2_NOB,K_NO2_NOB,Y_HET,Y_EPS,Y_AOB,Y_NOB,Y_I,ETA_H
REAL(8),SAVE::DIF_COEF_S,DIF_COEF_O2,DIF_COEF_NO2,DIF_COEF_NO3,DIF_COEF_NH4

END MODULE GLOBAL_VARIABLES

!IbM VARIABLES

MODULE IbM_VARIABLES
IMPLICIT NONE

INTEGER::BAC_N,N_FLOCS,N_COLONY_AOB,N_COLONY_NOB,BIOREACTOR,BAC_N_PREVIOUS
REAL(8),ALLOCATABLE,SAVE::BAC_M(:),BAC_MSHOV(:),BAC_E_D(:),BAC_R(:),BAC_RA(:),BAC_X(:),BAC_Y(:),BAC_Z(:),BAC_MMAX(:),SHOVING_VECTOR(:,:),RX(:),RE(:),RD(:),RCOL(:),BAC_RATE(:,:)
REAL(8),ALLOCATABLE,SAVE::BAC_M0(:),BAC_MSHOV0(:),BAC_E_D0(:),BAC_R0(:),BAC_RA0(:),BAC_X0(:),BAC_Y0(:),BAC_Z0(:),BAC_MMAX0(:),FLOC_CENTER(:),BAC_RATE0(:,:)
INTEGER,ALLOCATABLE,SAVE::BAC_S(:),BAC_C(:),BIOMASS_OCCUPANCY(:,:,:),BAC_S0(:),BAC_C0(:),BAC_DEAD0(:),BAC_DEAD(:)
INTEGER,SAVE::N_SINGLE_ATTACH,N_HET,N_AOB,N_NOB,N_EPS,N_INERT,N_EPS_DISSOLVED,N_SHOVING_INTERVAL,SOLVE_ONLY_BIOMASS
REAL(8),SAVE::MASS_HET,MASS_AOB,MASS_NOB,MASS_EPS,MASS_INERT,BAC_RHO,BAC_RHOD,BAC_RHOE,R_FLOC,M_DECAY_HET,M_DECAY_AOB,M_DECAY_NOB,SHOVING_FACTOR,MFLOC_NEW,MFLOC_OLD,DIVISION_FRACTION,NFLOCS,FLOC_RADIUS,FLOC_VOL

END MODULE IbM_VARIABLES

!REACTOR VARIABLES

MODULE REACTOR_VARIABLES
IMPLICIT NONE
REAL(8),SAVE::S_O2_R,S_O2_R_INLET,S_O2_SAT,S_NH4_R,S_NH4_R_INLET,S_NO2_R,S_NO2_R_INLET,S_NO3_R,S_NO3_R_INLET,S_S_R,S_S_R_INLET,V_R,M_BIOMASS,ALPHA,BETA,HRT,SRT,Q_O2

END MODULE REACTOR_VARIABLES


!========================================================================   
    
MODULE BCND  !DEFINE VARIABLES FOR BOUNDARY CONDITIONS
IMPLICIT NONE
INTEGER,SAVE::XBCS,YBCS,ZBCS,I_BC
REAL(8),ALLOCATABLE,SAVE::XBPS(:,:),XBNS(:,:),YBPS(:,:),YBNS(:,:),ZBPS(:,:),ZBNS(:,:)

END MODULE BCND

!========================================================================
SUBROUTINE DOMAIN   !DEFINE COMPUTATIONAL DOMAIN
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ,LX,LY,LZ,DX,DY,DZ,XMIN,XMAX,YMIN,YMAX,ZMIN,ZMAX
IMPLICIT NONE

XMIN=-100.D-6   !Chosen
XMAX=100.D-6    !Chosen
YMIN=-100.D-6   !Chosen
YMAX=100.D-6    !Chosen
ZMIN=-100.D-6   !Chosen
ZMAX=100.D-6    !Chosen

LX=XMAX-XMIN
LY=YMAX-YMIN
LZ=ZMAX-ZMIN

MX=20   !Chosen
MY=20   !Chosen
MZ=20   !Chosen

DX=LX/MX
DY=LY/MY
DZ=LZ/MZ

END SUBROUTINE DOMAIN
!=================================================================  
SUBROUTINE PARAMETERS  !DEFINE PARAMETERS
USE GLOBAL_VARIABLES,ONLY:DT_BIO,DT_PHY,TIME_PHY,TIME_BIO,TOTAL_TIME_BIO,TOTAL_TIME_PHY,MU_M_HET,MU_M_AOB,MU_M_NOB,B_HET,B_EPS,B_AOB,B_NOB,K_O2_HET,K_S_HET,K_NO2_HET,K_NO3_HET,K_O2_AOB,K_NH4_AOB,K_O2_NOB,K_NO2_NOB,Y_HET,Y_EPS,Y_AOB,Y_NOB,Y_I,ETA_H,N_GROWTH,DIF_COEF_S,DIF_COEF_O2,DIF_COEF_NO2,DIF_COEF_NO3,DIF_COEF_NH4,MASS_TRANSFER
USE IbM_VARIABLES,ONLY:BAC_N,MASS_HET,MASS_AOB,MASS_NOB,MASS_EPS,MASS_INERT,BAC_RHO,BAC_RHOD,BAC_RHOE,N_SINGLE_ATTACH,SHOVING_FACTOR,DIVISION_FRACTION,RCOL,BIOREACTOR,N_SHOVING_INTERVAL,SOLVE_ONLY_BIOMASS
USE	REACTOR_VARIABLES,ONLY:V_R,ALPHA,BETA,HRT,SRT,Q_O2,M_BIOMASS

IMPLICIT NONE

!KINETIC AND STOICHIOMETRIC

MU_M_HET=6.D0       !Ofiteru et al. (2014) !6.D0
MU_M_AOB=3.d0 !2.76D0     !PICIOUREANU ET AL. (2004) !0.76D0     !Ofiteru et al. (2014)
MU_M_NOB=3.d0 !2.81D0     !PICIOUREANU ET AL. (2004)!0.81D0     !Ofiteru et al. (2014)

B_HET=0.4D0         !Ofiteru et al. (2014)
B_EPS=0.17D0        !Ofiteru et al. (2014)
B_AOB=0.11D0        !Ofiteru et al. (2014)
B_NOB=0.11D0        !Ofiteru et al. (2014)

K_O2_HET=0.81D0     !Ofiteru et al. (2014)
K_S_HET=1.D-2       !Ofiteru et al. (2014)
K_NO2_HET=0.3D-3    !Ofiteru et al. (2014)
K_NO3_HET=0.3D-3    !Ofiteru et al. (2014)
K_O2_AOB=0.5D-3     !Ofiteru et al. (2014)
K_NH4_AOB=1.D-3     !Ofiteru et al. (2014)
K_O2_NOB=0.68D-3    !Ofiteru et al. (2014)
K_NO2_NOB=1.3D-3    !Ofiteru et al. (2014)

Y_HET=0.61D0        !Ofiteru et al. (2014)
Y_EPS=0.18D0        !Ofiteru et al. (2014)
Y_AOB=0.33D0        !Ofiteru et al. (2014)
Y_NOB=0.083D0       !Ofiteru et al. (2014)
Y_I=0.4D0           !Ofiteru et al. (2014)
ETA_H=0.6D0         !Ofiteru et al. (2014)

!IbM PARAMETERS

BAC_N=5             !Ofiteru et al. (2014)
MASS_HET=1.D-16     !Ofiteru et al. (2014)
MASS_AOB=1.D-16     !Ofiteru et al. (2014)
MASS_NOB=1.D-16     !Ofiteru et al. (2014)
MASS_EPS=2.6D-17    !Ofiteru et al. (2014)
MASS_INERT=1.1E-16  !Ofiteru et al. (2014)

BAC_RHO=150.D0      !iDynoMiCS
BAC_RHOD=105.D0     !Assumed as in Dana code
BAC_RHOE=30.D0      !iDynoMiCS 

SHOVING_FACTOR=1.1D0    !Chosen as in Dana code
N_SHOVING_INTERVAL=1    

N_GROWTH=200
N_SINGLE_ATTACH=10000      !Assumed

DIVISION_FRACTION=0.5D0 !Assumed as in Dana code

RCOL=(/2.5D0,2.0D0/)    !Assumed as in Dana code


M_BIOMASS=0.06D0        !Ofiteru et al. (2014)  
BIOREACTOR=0            !ON=1; OFF=0
!REACTOR PARAMETERS

V_R=1.D0            !Ofiteru et al. (2014)
ALPHA=0.2D0         !Ofiteru et al. (2014)
BETA=0.01D0         !Ofiteru et al. (2014)
HRT=7.D0/24.D0      !Ofiteru et al. (2014)
SRT=HRT*(ALPHA+BETA)/BETA/(1.D0+ALPHA)      !Ofiteru et al. (2014)

Q_O2=0.5D0      !Ofiteru et al. (2014)

SOLVE_ONLY_BIOMASS=0   !1=ONLY BIOMASS, 0=WHOLE COMPUTATIONAL DOMAIN
IF ((SOLVE_ONLY_BIOMASS .NE. 0) .AND. (SOLVE_ONLY_BIOMASS .NE. 1)) THEN
    PRINT*,'WRONG VALUE FOR "SOLVE_ONLY_BIOMASS", CHECK PARAMETERS'
    PAUSE
END IF


!DIFFUSION COEFFICIENTS IN WATER
DIF_COEF_S=4.32D-5 
DIF_COEF_O2=1.73D-4
DIF_COEF_NO2=1.04D-4
DIF_COEF_NO3=1.04D-4
DIF_COEF_NH4=1.21D-4

MASS_TRANSFER=1  !1=ON, 0=OFF, WHTHER MASS TRANSFER EQUATION IS SOLVED OR NOT
IF ((MASS_TRANSFER .NE. 0) .AND. (MASS_TRANSFER .NE. 1)) THEN
    PRINT*,'WRONG VALUE FOR "MASS_TRANSFER", CHECK PARAMETERS'
    PAUSE
END IF


!TIME 

DT_PHY=50.D-3/(3600*24)/20 !TIME IN DAYS

!TOTAL_TIME_PHY=1.D-6		!TIME IN DAYS, THIS IS CALCULATED IN SUBROUTINE DIF_COEF BASED ON DIFFUSION COEFFICIENTS

DT_BIO=0.01D0
TOTAL_TIME_BIO=2*DT_BIO		!TIME IN DAYS

END SUBROUTINE PARAMETERS
!================================================================== 
SUBROUTINE DIF_COEF()  !DEFINE DIFFUSION COEFFICIENTS
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ,D_O2,D_NO2,D_NO3,D_NH4,D_S,LX,LY,LZ,DX,DY,DZ,DT_PHY,TOTAL_TIME_PHY,DIF_COEF_S,DIF_COEF_O2,DIF_COEF_NO2,DIF_COEF_NO3,DIF_COEF_NH4
USE IbM_VARIABLES,ONLY:BIOMASS_OCCUPANCY
IMPLICIT NONE
INTEGER::I,J,K
REAL(8)::MIN_DIF,MAX_DIF,CONST,DIF_VECTOR(5)

CONST=0.8D0

D_O2=DIF_COEF_O2
D_NO2=DIF_COEF_NO2
D_NO3=DIF_COEF_NO3
D_NH4=DIF_COEF_NH4
D_S=DIF_COEF_S    


DO I=1,MX
    DO J=1,MY
        DO K=1,MZ
			
            !VERSION2 IMPROVEMENTS
            IF (BIOMASS_OCCUPANCY(I,J,K)==1) THEN   !DIFFUSION COEF WITHIN BIOMASS IS ABOUT 80% (iDynoMiCS) 
                D_O2(I,J,K)=DIF_COEF_O2*CONST
			    D_NO2(I,J,K)=DIF_COEF_NO2*CONST
                D_NO3(I,J,K)=DIF_COEF_NO3*CONST
                D_NH4(I,J,K)=DIF_COEF_NH4*CONST
                D_S(I,J,K)=DIF_COEF_S*CONST    
            END IF
        END DO
    END DO
END DO
DIF_VECTOR=CONST*(/DIF_COEF_O2,DIF_COEF_NO2,DIF_COEF_NO3,DIF_COEF_NH4,DIF_COEF_S/)
MIN_DIF=MINVAL(DIF_VECTOR)
MAX_DIF=MAXVAL(DIF_VECTOR)

DT_PHY=((DX*DY*DZ)**(2.D0/3.D0))/MAX_DIF/8.D0


PRINT*,DT_PHY
!PAUSE

TOTAL_TIME_PHY=((LX*LY*LZ/8.D0)**(2.D0/3.D0))/MIN_DIF

TOTAL_TIME_PHY=1.D-5 !SET VALUE

PRINT*,TOTAL_TIME_PHY
!PAUSE
    
END SUBROUTINE DIF_COEF
!================================================================== 
SUBROUTINE IC() !INITIAL CONDITIONS
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ,LX,LY,LZ,DX,DY,DZ,UX,UY,UZ,S_O2,S_NO2,S_NO3,S_NH4,S_S,R_O2,X_HET,X_AOB,X_NOB,X_EPS,X_S,X_I
USE IbM_VARIABLES
USE	REACTOR_VARIABLES,ONLY:S_O2_R,S_O2_R_INLET,S_O2_SAT,S_NH4_R,S_NH4_R_INLET,S_NO2_R,S_NO2_R_INLET,S_NO3_R,S_NO3_R_INLET,S_S_R,S_S_R_INLET,M_BIOMASS
IMPLICIT NONE
INTEGER::I,J,K
REAL(8)::PI

PI=4.D0*DATAN(1.D0)

UX=0.D0
UY=0.D0
UZ=0.D0



X_HET=0.000D0
X_AOB=0.000D0
X_NOB=0.000D0
X_EPS=0.000D0
X_S=0.000D0
X_I=0.000D0



DO I=1,MX
    DO J=1,MY
        DO K=1,MZ
			IF (ABS(I-MX/2-1)<MX/4 .AND.ABS(J-MY/2-1)<MY/4 .AND. ABS(K-MZ/2-1)<MZ/4 ) THEN

				X_HET(I,J,K)=0.0D0
				X_AOB(I,J,K)=0.0D0
				X_NOB(I,J,K)=0.0D0
				X_EPS(I,J,K)=0.0D0
				X_S(I,J,K)=0.0D0
				X_I(I,J,K)=0.0D0
			END IF
		END DO
	END DO
END DO

!R_O2=0.D0

!TIME=0.D0

!REACTOR VARIABLES
S_O2_R_INLET=5.D-3
S_O2_R=S_O2_R_INLET
S_O2_SAT=9.E-3

S_NH4_R_INLET=40.D-3
S_NH4_R=S_NH4_R_INLET

S_NO2_R_INLET=1.D-3
S_NO2_R=S_NO2_R_INLET

S_NO3_R_INLET=1.D-4
S_NO3_R=S_NO3_R_INLET

S_S_R_INLET=40.D-3
S_S_R=S_S_R_INLET


S_O2=S_O2_R
S_NO2=S_NO2_R
S_NO3=S_NO3_R
S_NH4=S_NH4_R
S_S=S_S_R


!PRINT*,S_NO2
!PAUSE


!IbM VARIABLES

BAC_X=(/LX/2,LX/2+DX/10,LX/2+DX/10,LX/2-DX/10,LX/2-DX/10/)
BAC_Y=(/LY/2,LY/2+DY/10,LY/2-DY/10,LY/2+DY/10,LY/2-DY/10/)
BAC_Z=(/LZ/2,LZ/2,LZ/2,LZ/2,LZ/2/)


BAC_M=(/MASS_HET,MASS_AOB,MASS_NOB,0.D0,0.D0/)
BAC_E_D=(/MASS_EPS,0.D0,0.D0,MASS_EPS,MASS_INERT/)
BAC_MSHOV=BAC_M+BAC_E_D

BAC_S=(/1,2,3,4,5/)
BAC_C=(/0,1,2,0,0/)

BAC_MMAX=(/2*MASS_HET,2*MASS_AOB,2*MASS_NOB/)  !CRITERIA FOR DIVISION

BAC_DEAD=0

M_DECAY_HET=0.D0
M_DECAY_AOB=0.D0
M_DECAY_NOB=0.D0

NFLOCS=M_BIOMASS/(SUM(BAC_M+BAC_E_D))




!PRINT*,NFLOCS,M_BIOMASS/SUM(BAC_M+BAC_E_D)
!PAUSE

BAC_R=((BAC_M/BAC_RHO+BAC_E_D/BAC_RHOE)*3/(4*PI))**(1.D0/3.D0)
BAC_RA=((BAC_M/BAC_RHO)*3/(4*PI))**(1.D0/3.D0)

N_HET=1
N_AOB=1
N_NOB=1
N_EPS=1
N_INERT=1


N_COLONY_AOB=1
N_COLONY_NOB=1

N_EPS_DISSOLVED=0
FLOC_CENTER(1)=LX/2.D0
FLOC_CENTER(2)=LY/2.D0
FLOC_CENTER(3)=LZ/2.D0


END SUBROUTINE IC
!=================================================================   
SUBROUTINE BC_S()  ! BOUNDARY CONDITIONS FOR S
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ
USE REACTOR_VARIABLES,ONLY:S_S_R
USE IbM_VARIABLES,ONLY:BIOREACTOR
USE BCND
IMPLICIT NONE
INTEGER::I,J,K
REAL(8)::BC

I_BC=2    !PERIODIC=0, FIXED VALUES=1, ZERO NORMAL DERIVATIVE=2

XBCS=I_BC
YBCS=I_BC
ZBCS=I_BC

IF (BIOREACTOR==1) THEN
    XBCS=1
    YBCS=1
    ZBCS=1
END IF

BC=S_S_R

XBPS(:,:)=BC
XBNS(:,:)=BC 
YBPS(:,:)=BC
YBNS(:,:)=BC
ZBPS(:,:)=BC
ZBNS(:,:)=BC

END SUBROUTINE BC_S

!=================================================================   
SUBROUTINE BC_O2()  ! BOUNDARY CONDITIONS FOR O2
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ
USE REACTOR_VARIABLES,ONLY:S_O2_R
USE IbM_VARIABLES,ONLY:BIOREACTOR
USE BCND
IMPLICIT NONE
INTEGER::I,J,K

REAL(8)::BC

I_BC=2

XBCS=I_BC
YBCS=I_BC
ZBCS=I_BC

IF (BIOREACTOR==1) THEN
    XBCS=1
    YBCS=1
    ZBCS=1
END IF
BC=S_O2_R

XBPS(:,:)=BC
XBNS(:,:)=BC 
YBPS(:,:)=BC
YBNS(:,:)=BC
ZBPS(:,:)=BC
ZBNS(:,:)=BC

 END SUBROUTINE BC_O2

!=================================================================   
SUBROUTINE BC_NH4()  ! BOUNDARY CONDITIONS FOR NH4
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ
USE REACTOR_VARIABLES,ONLY:S_NH4_R
USE IbM_VARIABLES,ONLY:BIOREACTOR
USE BCND
IMPLICIT NONE
INTEGER::I,J,K

REAL(8)::BC

I_BC=2

XBCS=I_BC
YBCS=I_BC
ZBCS=I_BC

IF (BIOREACTOR==1) THEN
    XBCS=1
    YBCS=1
    ZBCS=1
END IF
BC=S_NH4_R

XBPS(:,:)=BC
XBNS(:,:)=BC 
YBPS(:,:)=BC
YBNS(:,:)=BC
ZBPS(:,:)=BC
ZBNS(:,:)=BC

 END SUBROUTINE BC_NH4

!=================================================================   
SUBROUTINE BC_NO2()  ! BOUNDARY CONDITIONS FOR NO2
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ
USE REACTOR_VARIABLES,ONLY:S_NO2_R
USE IbM_VARIABLES,ONLY:BIOREACTOR
USE BCND
IMPLICIT NONE
INTEGER::I,J,K

REAL(8)::BC

I_BC=2

XBCS=I_BC
YBCS=I_BC
ZBCS=I_BC

IF (BIOREACTOR==1) THEN
    XBCS=1
    YBCS=1
    ZBCS=1
END IF
BC=S_NO2_R

XBPS(:,:)=BC
XBNS(:,:)=BC
YBPS(:,:)=BC
YBNS(:,:)=BC
ZBPS(:,:)=BC
ZBNS(:,:)=BC

 END SUBROUTINE BC_NO2

!=================================================================   
SUBROUTINE BC_NO3()  ! BOUNDARY CONDITIONS FOR NO3
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ
USE REACTOR_VARIABLES,ONLY:S_NO3_R
USE IbM_VARIABLES,ONLY:BIOREACTOR
USE BCND
IMPLICIT NONE
INTEGER::I,J,K
REAL(8)::BC

I_BC=2

XBCS=I_BC
YBCS=I_BC
ZBCS=I_BC

IF (BIOREACTOR==1) THEN
    XBCS=1
    YBCS=1
    ZBCS=1
END IF
BC=S_NO3_R

XBPS(:,:)=BC
XBNS(:,:)=BC 
YBPS(:,:)=BC
YBNS(:,:)=BC
ZBPS(:,:)=BC
ZBNS(:,:)=BC

 END SUBROUTINE BC_NO3
!================================================================  

    
DOUBLE PRECISION FUNCTION GS(S,I,J,K) !GHOST POINT VALUES OF SUBSTRATE
USE GLOBAL_VARIABLES, ONLY:MX,MY,MZ
USE BCND
IMPLICIT NONE
INTEGER::I,J,K
REAL(8)::S(MX,MY,MZ)
IF (I==1) THEN
    IF (XBCS==0) THEN
        GS=S(MX,J,K)
    END IF
	IF (XBCS==1) THEN
        GS=2*XBNS(J,K)-S(I,J,K)
    END IF
    
    IF (XBCS==2) THEN
        GS=S(I,J,K)
    END IF
    

ELSE IF (I==MX) THEN  
	IF (XBCS==0) THEN
        GS=S(1,J,K)
    END IF
    IF (XBCS==1) THEN
        GS=2*XBPS(J,K)-S(I,J,K)
    END IF
    
    IF (XBCS==2) THEN
        GS=S(I,J,K)
    END IF
    
ELSE IF (J==1) THEN
	IF (YBCS==0) THEN 
        GS=S(I,MY,K)
    END IF
    IF (YBCS==1) THEN 
        GS=2*YBNS(I,K)-S(I,J,K)
    END IF
    IF (YBCS==2) THEN
        GS=S(I,J,K)
    END IF
    
ELSE IF (J==MY) THEN 
	IF (YBCS==0) THEN 
        GS=S(I,1,K)
    END IF
    IF (YBCS==1) THEN
        GS=2*YBPS(I,K)-S(I,J,K) 
    END IF
    IF (YBCS==2) THEN
        GS=S(I,J,K)
    END IF
ELSE IF (K==1) THEN
	IF (ZBCS==0) THEN
        GS=S(I,J,MZ)
    END IF
    IF (ZBCS==1) THEN
        GS=2*ZBNS(I,J)-S(I,J,K)
    END IF
    IF (ZBCS==2) THEN
        GS=S(I,J,K)
    END IF
ELSE IF (K==MZ) THEN 
	IF (ZBCS==0) THEN
        GS=S(I,J,1)
    END IF
    IF (ZBCS==1) THEN
        GS=2*ZBPS(I,J)-S(I,J,K) 
    END IF
    IF (ZBCS==2) THEN
        GS=S(I,J,K)
    END IF
END IF
       
END FUNCTION GS 

!============================================================================
DOUBLE PRECISION FUNCTION MAX_VALUE(MX,MY,MZ,S) !CALCULATE MAXIMUM VALUE
IMPLICIT NONE
INTEGER::MX,MY,MZ,I,J,K
REAL(8)::S(MX,MY,MZ),S_MAX

S_MAX=0.D0

DO I=1,MX
	DO J=1,MY
		DO K=1,MZ
			IF (S_MAX<S(I,J,K)) THEN
				S_MAX=S(I,J,K)
			END IF
		END DO
	END DO
END DO
MAX_VALUE=S_MAX	
END FUNCTION MAX_VALUE

!==============================================================================   
SUBROUTINE SUBSTRATE_TRANSPORT(SUBSTRATE_TYPE,MX,MY,MZ,DX,DY,DZ,UX,UY,UZ,R_S,D_S,DT,S,S_RESIDUAL)  !SUBSTRATE DISTRIBUTION:CONVECTION-DIFFUSION-REACTION

!USE GLOBAL_VARIABLES,ONLY:Y_HET
USE REACTOR_VARIABLES,ONLY:S_S_R,S_O2_R,S_NO2_R,S_NO3_R,S_NH4_R
USE IbM_VARIABLES,ONLY:BIOMASS_OCCUPANCY,SOLVE_ONLY_BIOMASS,BIOREACTOR
USE BCND

IMPLICIT NONE
INTEGER::MX,MY,MZ,I,J,K,SUBSTRATE_TYPE,DOMAIN(MX,MY,MZ)
REAL(8)::S(MX,MY,MZ),R_S(MX,MY,MZ),DX,DY,DZ,D_S(MX,MY,MZ),JX1,JY1,JZ1,JX2,JY2,JZ2,DT,S_NEW(MX,MY,MZ),UX(MX+1,MY,MZ),UY(MX,MY+1,MZ),UZ(MX,MY,MZ+1),CONV_X,CONV_Y,CONV_Z,DIF_TERM,CONV_TERM,GS,UX_AVG,UY_AVG,UZ_AVG,S_RESIDUAL,CONST_S
REAL(8),SAVE::SUM_S
!PRINT*,DT
S_RESIDUAL=0.D0

IF (SOLVE_ONLY_BIOMASS==1) THEN
    DOMAIN=BIOMASS_OCCUPANCY
ELSE IF (SOLVE_ONLY_BIOMASS==0) THEN
    DOMAIN=1
END IF

SUM_S=SUM(S)

!PRINT*,Y_HET


DO I=1,MX
  ! PAUSE
    DO J=1,MY
        DO K=1,MZ
            
            IF (DOMAIN(I,J,K)==1 ) THEN
       !     PAUSE
            UX_AVG=(UX(I+1,J,K)+UX(I,J,K))/2.D0
            UY_AVG=(UY(I,J+1,K)+UY(I,J,K))/2.D0
            UZ_AVG=(UZ(I,J,K+1)+UZ(I,J,K))/2.D0
            !========FLUX AND CONVECTIVE TERMS IN X DIRECTION
            IF (I>1 .AND. I<MX ) THEN
                JX2=0.5d0*(D_S(I+1,J,K)+D_S(I,J,K))*(S(I+1,J,K)-S(I,J,K))/(DX)
                JX1=0.5d0*(D_S(I,J,K)+D_S(I-1,J,K))*(S(I,J,K)-S(I-1,J,K))/(DX)
                CONV_X=UX_AVG*(S(I+1,J,K)-S(I-1,J,K))/(2*DX)
            ELSE IF (I==1 ) THEN
                
                JX2=0.5d0*(D_S(I+1,J,K)+D_S(I,J,K))*(S(I+1,J,K)-S(I,J,K))/(DX)
                JX1=D_S(I,J,K)*(S(I,J,K)-GS(S,I,J,K))/(DX)  
                CONV_X=UX_AVG*(S(I+1,J,K)-GS(S,I,J,K))/(2*DX)
    !            PRINT*,I,JX1,JX2
            ELSE IF (I==MX ) THEN
                
                JX2=D_S(I,J,K)*(GS(S,I,J,K)-S(I,J,K))/(DX)
                JX1=0.5d0*(D_S(I,J,K)+D_S(I-1,J,K))*(S(I,J,K)-S(I-1,J,K))/(DX)
                CONV_X=UX_AVG*(GS(S,I,J,K)-S(I-1,J,K))/(2*DX)
            END IF
            
            !========FLUX AND CONVECTIVE TERMS IN Y DIRECTION
            IF (J>1 .AND. J<MY ) THEN
                JY2=0.5d0*(D_S(I,J+1,K)+D_S(I,J,K))*(S(I,J+1,K)-S(I,J,K))/(DY)
                JY1=0.5d0*(D_S(I,J,K)+D_S(I,J-1,K))*(S(I,J,K)-S(I,J-1,K))/(DY)
                CONV_Y=UY_AVG*(S(I,J+1,K)-S(I,J-1,K))/(2*DY)
            ELSE IF (J==1) THEN
                
                JY2=0.5d0*(D_S(I,J+1,K)+D_S(I,J,K))*(S(I,J+1,K)-S(I,J,K))/(DY)
                JY1=D_S(I,J,K)*(S(I,J,K)-GS(S,I,J,K))/(DY)
                CONV_Y=UY_AVG*(S(I,J+1,K)-GS(S,I,J,K))/(2*DY)
            ELSE IF (J==MY) THEN
                
                JY2=D_S(I,J,K)*(GS(S,I,J,K)-S(I,J,K))/(DY)
                JY1=0.5d0*(D_S(I,J,K)+D_S(I,J-1,K))*(S(I,J,K)-S(I,J-1,K))/(DY)
                CONV_Y=UY_AVG*(GS(S,I,J,K)-S(I,J-1,K))/(2*DY)
            END IF 
            
            !========FLUX AND CONVECTIVE TERMS IN Z DIRECTION
            IF (K>1 .AND. K<MZ) THEN
                JZ2=0.5d0*(D_S(I,J,K+1)+D_S(I,J,K))*(S(I,J,K+1)-S(I,J,K))/(DZ)
                JZ1=0.5d0*(D_S(I,J,K)+D_S(I,J,K-1))*(S(I,J,K)-S(I,J,K-1))/(DZ)
                CONV_Z=UZ_AVG*(S(I,J,K+1)-S(I,J,K-1))/(2*DZ)
            ELSE IF (K==1) THEN
                
                JZ2=0.5d0*(D_S(I,J,K+1)+D_S(I,J,K))*(S(I,J,K+1)-S(I,J,K))/(DZ)
                JZ1=D_S(I,J,K)*(S(I,J,K)-GS(S,I,J,K))/(DZ)
                CONV_Z=UZ_AVG*(S(I,J,K+1)-GS(S,I,J,K))/(2*DZ)
                
     !           PRINT*,D_S(I,J,K)
            ELSE IF (K==MZ) THEN
                
                JZ2=D_S(I,J,K)*(GS(S,I,J,K)-S(I,J,K))/(DZ)
                JZ1=0.5d0*(D_S(I,J,K)+D_S(I,J,K-1))*(S(I,J,K)-S(I,J,K-1))/(DZ)
                CONV_Z=UZ_AVG*(GS(S,I,J,K)-S(I,J,K-1))/(2*DZ)
            END IF             
               
                        
            DIF_TERM=(JX2-JX1)/(DX)+(JY2-JY1)/(DY)+(JZ2-JZ1)/(DZ) 
            
            CONV_TERM=CONV_X+CONV_Y+CONV_Z
            
            S_NEW(I,J,K)=S(I,J,K)+DT*(-CONV_TERM + DIF_TERM + R_S(I,J,K))
            
            
            
            ELSE IF (DOMAIN(I,J,K)==0 ) THEN  !VERSION2 IMPROVEMENTS: TRANSPORT EQUATION IS SOLVED WITHIN ONLY BIOMASS. OUTSIDE THE BIOMASS IT IS CONSTANT AS IN BOUNDARY.
                 IF  (BIOREACTOR==1) THEN
                    SELECT CASE (SUBSTRATE_TYPE)
                  
                        CASE(1)
                            S_NEW(I,J,K)=S_S_R
                        CASE(2)
                            S_NEW(I,J,K)=S_NH4_R 
                        CASE(3)
                            S_NEW(I,J,K)=S_NO2_R   
                        CASE(4)
                            S_NEW(I,J,K)=S_NO3_R  
                        CASE(5)
                            S_NEW(I,J,K)=S_O2_R  
                     END SELECT
                END IF
                
                IF (BIOREACTOR==0) THEN
                    IF (I_BC==1) THEN
                        
                        SELECT CASE (SUBSTRATE_TYPE)
                  
                            CASE(1)
                                S_NEW(I,J,K)=S_S_R
                            CASE(2)
                                S_NEW(I,J,K)=S_NH4_R 
                            CASE(3)
                                S_NEW(I,J,K)=S_NO2_R   
                            CASE(4)
                                S_NEW(I,J,K)=S_NO3_R  
                            CASE(5)
                                S_NEW(I,J,K)=S_O2_R  
                        END SELECT
                     ELSE IF (I_BC==0) THEN   
                       S_NEW(I,J,K)=SUM_S/(MX*MY*MZ)
                     END IF
                     
                       
                END IF
            END IF
            
            
            SELECT CASE (SUBSTRATE_TYPE)
                CASE(1)
                   CONST_S=S_S_R
                CASE(2)
                   CONST_S=S_NH4_R 
                CASE(3)
                   CONST_S=S_NO2_R   
                CASE(4)
                   CONST_S=S_NO3_R  
                CASE(5)
                   CONST_S=S_O2_R  
              END SELECT   
              
              
            IF (CONST_S<=0.D0) CONST_S=1.D0 
			
			IF (S_NEW(I,J,K)<0.D0) THEN
              !  PRINT*,'NEGATIVE CONCENTRATION',S_NEW(I,J,K)
              !  PAUSE
              !  S_NEW(I,J,K)=0.D0
                
            END IF
            
			
			
			
			IF (S_RESIDUAL<DABS((S_NEW(I,J,K)-S(I,J,K))/CONST_S)) THEN
				S_RESIDUAL=DABS((S_NEW(I,J,K)-S(I,J,K))/CONST_S)
			!        IF ( S_RESIDUAL>10) THEN
             !       PRINT*, S_NEW(I,J,K),S(I,J,K),I,J,K,CONST_S,S_RESIDUAL
              !      PAUSE
               !      END IF
            
            END IF
				
        !  PRINT*,S_RESIDUAL
         !   IF (I==MX/2 .AND. J==MY/2 .AND. K==1) THEN
          !      PRINT*,K, S_NEW(I,J,K)
         !   END IF
        !    IF (I==MX/2 .AND. J==MY/2 .AND. K==MZ) THEN
         !       PRINT*,K, S_NEW(I,J,K)
        !    END IF
             
        END DO
    END DO
END DO



S(1:MX,1:MY,1:MZ)=S_NEW(1:MX,1:MY,1:MZ)



!PRINT*,MX,SIZE(UX)


END SUBROUTINE SUBSTRATE_TRANSPORT


!=====================BIOMASS GROWTH FUNCTIONS===============================

!	1.AEROBIC GROWTH OF HETEROTROPIC HET

DOUBLE PRECISION FUNCTION GR_HET_O2(MU_M_HET,K_S_HET,K_O2_HET,S_S,S_O2,X_HET)
IMPLICIT NONE
REAL(8)::MU_M_HET,K_S_HET,K_O2_HET,S_S,S_O2,X_HET

	GR_HET_O2=MU_M_HET*(S_S/(K_S_HET+S_S)) * (S_O2/(K_O2_HET+S_O2))*X_HET

END FUNCTION GR_HET_O2

!	2.AEROBIC GROWTH OF AMONIA OXIDIZERS, AOB
DOUBLE PRECISION FUNCTION GR_AOB_O2(MU_M_AOB,K_NH4_AOB,K_O2_AOB,S_NH4,S_O2,X_AOB)
IMPLICIT NONE
REAL(8)::MU_M_AOB,K_NH4_AOB,K_O2_AOB,S_NH4,S_O2,X_AOB

	GR_AOB_O2=MU_M_AOB*(S_NH4/(K_NH4_AOB+S_NH4))* (S_O2/(K_O2_AOB+S_O2))*X_AOB 
END FUNCTION GR_AOB_O2

!	3.AEROBIC GROWTH OF NITRITE OXIDIZERS, NOB
DOUBLE PRECISION FUNCTION GR_NOB_O2(MU_M_NOB,K_NO2_NOB,K_O2_NOB,S_NO2,S_O2,X_NOB)
IMPLICIT NONE
REAL(8)::MU_M_NOB,K_NO2_NOB,K_O2_NOB,S_NO2,S_O2,X_NOB

	GR_NOB_O2=MU_M_NOB*(S_NO2/(K_NO2_NOB+S_NO2))* (S_O2/(K_O2_NOB+S_O2))*X_NOB 
END FUNCTION GR_NOB_O2

!	4.ANOXIC GROWTH OF HETEROTROPHS ON NITRATE (DENITRIFICATION)
DOUBLE PRECISION FUNCTION GR_HET_NO3(ETA_H,MU_M_HET,K_S_HET,K_NO3_HET,K_O2_HET,S_S,S_NO3,S_O2,X_HET)
IMPLICIT NONE
REAL(8)::ETA_H,MU_M_HET,K_S_HET,K_NO3_HET,K_O2_HET,S_S,S_NO3,S_O2,X_HET

	GR_HET_NO3=ETA_H*MU_M_HET*(S_S/(K_S_HET+S_S))*(S_NO3/(K_NO3_HET+S_NO3))*(K_O2_HET/(K_O2_HET+S_O2))*X_HET

END FUNCTION GR_HET_NO3

!	5.ANOXIC GROWTH OF HETEROTROPHS ON NITRITE (DENITRIFICATION)
DOUBLE PRECISION FUNCTION GR_HET_NO2(ETA_H,MU_M_HET,K_S_HET,K_NO2_HET,K_O2_HET,S_S,S_NO2,S_O2,X_HET)
IMPLICIT NONE
REAL(8)::ETA_H,MU_M_HET,K_S_HET,K_NO2_HET,K_O2_HET,S_S,S_NO2,S_O2,X_HET

	GR_HET_NO2=ETA_H*MU_M_HET*(S_S/(K_S_HET+S_S))*(S_NO2/(K_NO2_HET+S_NO2))*(K_O2_HET/(K_O2_HET+S_O2))*X_HET

END FUNCTION GR_HET_NO2

!	6.DECAY OF HET
DOUBLE PRECISION FUNCTION DR_HET(B_HET,X_HET)
IMPLICIT NONE
REAL(8)::B_HET,X_HET

	DR_HET=B_HET*X_HET

END FUNCTION DR_HET
    
 !	7.DECAY OF AOB
DOUBLE PRECISION FUNCTION DR_AOB(B_AOB,X_AOB)
IMPLICIT NONE
REAL(8)::B_AOB,X_AOB

	DR_AOB=B_AOB*X_AOB

END FUNCTION DR_AOB

!	8.DECAY OF AOB
DOUBLE PRECISION FUNCTION DR_NOB(B_NOB,X_NOB)
IMPLICIT NONE
REAL(8)::B_NOB,X_NOB

	DR_NOB=B_NOB*X_NOB

END FUNCTION DR_NOB

!	9.DECAY OF EPS
DOUBLE PRECISION FUNCTION DR_EPS(B_EPS,X_EPS)
IMPLICIT NONE
REAL(8)::B_EPS,X_EPS

	DR_EPS=B_EPS*X_EPS

END FUNCTION DR_EPS

!=============================================================================
SUBROUTINE REACTION_RATES(R_S,R_NH4,R_NO2,R_NO3,R_O2) !REACTION RATE FOR MASS TRASPORT EQN: R_S
USE GLOBAL_VARIABLES, ONLY:MX,MY,MZ,X_HET,X_I,X_AOB,X_NOB,X_EPS,S_NH4,S_S,S_O2,S_NO3,S_NO2,Y_HET,Y_EPS,Y_I,Y_AOB,Y_NOB,MU_M_HET,MU_M_AOB,MU_M_NOB,K_S_HET,K_O2_HET,ETA_H,K_NO3_HET,K_NO2_HET,K_NH4_AOB,K_O2_AOB,K_NO2_NOB,K_O2_NOB,B_HET,B_AOB,B_NOB,B_EPS
IMPLICIT NONE
INTEGER::I,J,K
REAL(8)::R_S(MX,MY,MZ),R_NH4(MX,MY,MZ),R_NO2(MX,MY,MZ),R_NO3(MX,MY,MZ),R_O2(MX,MY,MZ),GR_HET_O2,GR_HET_NO3,GR_HET_NO2,GR_AOB_O2,GR_NOB_O2,DR_HET,DR_AOB,DR_NOB,DR_EPS,VAR1,VAR2,VAR3,VAR4,TERM1,TERM2,TERM3,TERM4

DO I=1,MX
	DO J=1,MY
		DO K=1,MZ
			
			!REACTION TERMS FOR S
			
			VAR1=S_S(I,J,K)
			VAR2=S_O2(I,J,K)
			VAR3=X_HET(I,J,K)
           !                    GR_HET_O2(MU_M_HET,K_S_HET,K_O2_HET,S_S,S_O2,X_HET) AEROBIC GROWTH OF HET
			TERM1=(-1.D0/Y_HET)*GR_HET_O2(MU_M_HET,K_S_HET,K_O2_HET,VAR1,VAR2,VAR3)

			!PRINT*,TERM1
			!PAUSE
			
			VAR1=S_S(I,J,K)
			VAR2=S_NO3(I,J,K)
			VAR3=S_O2(I,J,K)
			VAR4=X_HET(I,J,K)
            !                   GR_HET_NO3(ETA_H,MU_M_HET,K_S_HET,K_NO3_HET,K_O2_HET,S_S,S_NO3,S_O2,X_HET)  ANOXIC GROWTH OF HET ON NO3
			TERM2=(-1.D0/Y_HET)*GR_HET_NO3(ETA_H,MU_M_HET,K_S_HET,K_NO3_HET,K_O2_HET,VAR1,VAR2,VAR3,VAR4)

			VAR1=S_S(I,J,K)
			VAR2=S_NO2(I,J,K)
			VAR3=S_O2(I,J,K)
			VAR4=X_HET(I,J,K)
            !                     GR_HET_NO2(ETA_H,MU_M_HET,K_S_HET,K_NO2_HET,K_O2_HET,S_S,S_NO2,S_O2,X_HET)  ANOXIC GROWTH OF HET ON NO2          
			TERM3=(-1.D0/Y_HET)*GR_HET_NO2(ETA_H,MU_M_HET,K_S_HET,K_NO2_HET,K_O2_HET,VAR1,VAR2,VAR3,VAR4)

		!	VAR1=X_HET(I,J,K)
		!	VAR2=X_AOB(I,J,K)
		!	VAR3=X_NOB(I,J,K)
		!	VAR4=X_EPS(I,J,K)
			
	!		TERM4=(1-Y_I)*(DR_HET(B_HET,VAR1)+DR_AOB(B_AOB,VAR2)+DR_NOB(B_NOB,VAR3))+1.D0*DR_EPS(B_EPS,VAR4)  !DECAY OF HET+AOB+NOB+EPS !VERSION2 IMPROVEMENTS, DECAY MASS IS INCLUDED IN GROWTH CALCULATIONS

			R_S(I,J,K)=TERM1+TERM2+TERM3  !+TERM4
          !  IF (R_S(I,J,K)>0.0) PRINT*,'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR'
			!REACTION TERMS FOR O2

			VAR1=S_S(I,J,K)
			VAR2=S_O2(I,J,K)
			VAR3=X_HET(I,J,K)
                                            ! GR_HET_O2(MU_M_HET,K_S_HET,K_O2_HET,S_S,S_O2,X_HET)  AEROBIC GROWTH OF HET
			TERM1=(-(1.D0-Y_HET-Y_EPS)/Y_HET)*GR_HET_O2(MU_M_HET,K_S_HET,K_O2_HET,VAR1,VAR2,VAR3)
			
			VAR1=S_NH4(I,J,K)
			VAR2=S_O2(I,J,K)
			VAR3=X_AOB(I,J,K)
			                             !GR_AOB_O2(MU_M_AOB,K_NH4_AOB,K_O2_AOB,S_NH4,S_O2,X_AOB)  AEROBIC GROWTH OF AOB
			TERM2=(-(3.42D0-Y_AOB)/Y_AOB)*GR_AOB_O2(MU_M_AOB,K_NH4_AOB,K_O2_AOB,VAR1,VAR2,VAR3)

			VAR1=S_NO2(I,J,K)
			VAR2=S_O2(I,J,K)
			VAR3=X_NOB(I,J,K)
			                        !     GR_NOB_O2(MU_M_NOB,K_NO2_NOB,K_O2_NOB,S_NO2,S_O2,X_NOB)  AEROBIC GROWTH OF NOB
			TERM3=(-(1.15D0-Y_NOB)/Y_NOB)*GR_NOB_O2(MU_M_NOB,K_NO2_NOB,K_O2_NOB,VAR1,VAR2,VAR3)

			R_O2(I,J,K)=TERM1+TERM2+TERM3
			
			
			!REACTION TERMS FOR NH4

			VAR1=S_NH4(I,J,K)
			VAR2=S_O2(I,J,K)
			VAR3=X_AOB(I,J,K)

			                  ! GR_AOB_O2(MU_M_AOB,K_NH4_AOB,K_O2_AOB,S_NH4,S_O2,X_AOB)  AEROBIC GROWTH OF AOB
			TERM1=(-1.D0/Y_AOB)*GR_AOB_O2(MU_M_AOB,K_NH4_AOB,K_O2_AOB,VAR1,VAR2,VAR3)	
			
			R_NH4(I,J,K)=TERM1
			
            !REACTION TERMS FOR NO2

			VAR1=S_NH4(I,J,K)
			VAR2=S_O2(I,J,K)
			VAR3=X_AOB(I,J,K)
                             ! GR_AOB_O2(MU_M_AOB,K_NH4_AOB,K_O2_AOB,S_NH4,S_O2,X_AOB)   AEROBIC GROWTH OF AOB
			TERM1=(1.D0/Y_AOB)*GR_AOB_O2(MU_M_AOB,K_NH4_AOB,K_O2_AOB,VAR1,VAR2,VAR3)
			
			VAR1=S_NO2(I,J,K)
			VAR2=S_O2(I,J,K)
			VAR3=X_NOB(I,J,K)
			                !   GR_NOB_O2(MU_M_NOB,K_NO2_NOB,K_O2_NOB,S_NO2,S_O2,X_NOB)  AEROBIC GROWTH OF NOB
			TERM2=(-1.D0/Y_NOB)*GR_NOB_O2(MU_M_NOB,K_NO2_NOB,K_O2_NOB,VAR1,VAR2,VAR3)

			VAR1=S_S(I,J,K)
			VAR2=S_NO2(I,J,K)
			VAR3=S_O2(I,J,K)
			VAR4=X_HET(I,J,K)
                                    !                  GR_HET_NO2(ETA_H,MU_M_HET,K_S_HET,K_NO2_HET,K_O2_HET,S_S,S_NO2,S_O2,X_HET)  ANOXIC GROWTH OF HET ON NO2 
			TERM3=(-(1.D0-Y_HET-Y_EPS)/(1.71D0*Y_HET))*GR_HET_NO2(ETA_H,MU_M_HET,K_S_HET,K_NO2_HET,K_O2_HET,VAR1,VAR2,VAR3,VAR4)

			R_NO2(I,J,K)=TERM1+TERM2+TERM3
            
         !   IF (R_NO2(I,J,K)<0.0) PRINT*,'NO22222222222222222222222222222222222222222222',R_NO2(I,J,K),TERM1,TERM2,TERM3,X_NOB(I,J,K)

			!REACTION TERMS FOR NO3

			VAR1=S_NO2(I,J,K)
			VAR2=S_O2(I,J,K)
			VAR3=X_NOB(I,J,K)
                            !  GR_NOB_O2(MU_M_NOB,K_NO2_NOB,K_O2_NOB,S_NO2,S_O2,X_NOB)  AEROBIC GROWTH OF NOB
			TERM1=(1.D0/Y_NOB)*GR_NOB_O2(MU_M_NOB,K_NO2_NOB,K_O2_NOB,VAR1,VAR2,VAR3)

			VAR1=S_S(I,J,K)
			VAR2=S_NO3(I,J,K)
			VAR3=S_O2(I,J,K)
			VAR4=X_HET(I,J,K)
                                    !                  GR_HET_NO3(ETA_H,MU_M_HET,K_S_HET,K_NO3_HET,K_O2_HET,S_S,S_NO3,S_O2,X_HET)  ANOXIC GROWTH OF HET ON NO3
			TERM2=(-(1.D0-Y_HET-Y_EPS)/(2.86D0*Y_HET))*GR_HET_NO3(ETA_H,MU_M_HET,K_S_HET,K_NO3_HET,K_O2_HET,VAR1,VAR2,VAR3,VAR4)

			R_NO3(I,J,K)=TERM1+TERM2


		END DO
	END DO
END DO			


END SUBROUTINE REACTION_RATES
!==========================================================================

SUBROUTINE MASS_TRANSPORT_SOLVER(S_RESIDUAL)  !MASS TRANSPORT SOLVER
USE GLOBAL_VARIABLES
USE IbM_VARIABLES,ONLY:NFLOCS,BIOREACTOR
USE REACTOR_VARIABLES,ONLY:S_S_R,S_O2_R,S_NO2_R,S_NO3_R,S_NH4_R,S_S_R_INLET,S_O2_R_INLET,S_NO2_R_INLET,S_NO3_R_INLET,S_NH4_R_INLET,HRT,V_R,S_O2_SAT,Q_O2
USE BCND

IMPLICIT NONE
INTEGER::SUBSTRATE_TYPE
REAL(8)::RES_S,RES_NH4,RES_NO2,RES_NO3,RES_O2,S_RESIDUAL,R_I_R

!PRINT*,Y_HET

!PAUSE

!CALCULATE REACTION TERMS

S_RESIDUAL=0.D0

CALL REACTION_RATES(R_S,R_NH4,R_NO2,R_NO3,R_O2)

! UPDATE REACTOR VARIABLES===============


IF (TIME_PHY==0.D0  .AND. BIOREACTOR==1) THEN




!PRINT*,'*****************'
!PRINT*,SUM(R_S),NFLOCS
!PRINT*,'*****************'

R_I_R=DX*DY*DZ*SUM(R_S)*NFLOCS/V_R

S_S_R=S_S_R+DT_BIO*( (S_S_R_INLET-S_S_R)/HRT +R_I_R)

R_I_R=DX*DY*DZ*SUM(R_O2)*NFLOCS/V_R

S_O2_R=S_O2_R+DT_BIO*( (S_O2_R_INLET-S_O2_R)/HRT +R_I_R) + DT_BIO*Q_O2*(1.D0-S_O2_R/S_O2_SAT)


R_I_R=DX*DY*DZ*SUM(R_NO2)*NFLOCS/V_R

S_NO2_R=S_NO2_R+DT_BIO*( (S_NO2_R_INLET-S_NO2_R)/HRT +R_I_R)

!PRINT*,S_NO2_R


R_I_R=DX*DY*DZ*SUM(R_NO3)*NFLOCS/V_R

S_NO3_R=S_NO3_R+DT_BIO*( (S_NO3_R_INLET-S_NO3_R)/HRT +R_I_R)


R_I_R=DX*DY*DZ*SUM(R_NH4)*NFLOCS/V_R

S_NH4_R=S_NH4_R+DT_BIO*( (S_NH4_R_INLET-S_NH4_R)/HRT +R_I_R)

END IF





!========================================
!CALCULATE S DISTRIBUTION

CALL BC_S()
SUBSTRATE_TYPE=1 ! S
CALL SUBSTRATE_TRANSPORT(SUBSTRATE_TYPE,MX,MY,MZ,DX,DY,DZ,UX,UY,UZ,R_S,D_S,DT_PHY,S_S,RES_S)
	IF (S_RESIDUAL<RES_S) S_RESIDUAL=RES_S

!CALCULATE NH4 DISTRIBUTION



CALL BC_NH4()
SUBSTRATE_TYPE=2 ! S

CALL SUBSTRATE_TRANSPORT(SUBSTRATE_TYPE,MX,MY,MZ,DX,DY,DZ,UX,UY,UZ,R_NH4,D_NH4,DT_PHY,S_NH4,RES_NH4)
	IF (S_RESIDUAL<RES_NH4) S_RESIDUAL=RES_NH4
!PRINT*,RES_NH4
!CALCULATE NO2 DISTRIBUTION

CALL BC_NO2()

SUBSTRATE_TYPE=3 ! S

CALL SUBSTRATE_TRANSPORT(SUBSTRATE_TYPE,MX,MY,MZ,DX,DY,DZ,UX,UY,UZ,R_NO2,D_NO2,DT_PHY,S_NO2,RES_NO2)
	IF (S_RESIDUAL<RES_NO2) S_RESIDUAL=RES_NO2

!PRINT*,RES_NO2

!CALCULATE NO3 DISTRIBUTION

CALL BC_NO3()
SUBSTRATE_TYPE=4 ! S

CALL SUBSTRATE_TRANSPORT(SUBSTRATE_TYPE,MX,MY,MZ,DX,DY,DZ,UX,UY,UZ,R_NO3,D_NO3,DT_PHY,S_NO3,RES_NO3)
	IF (S_RESIDUAL<RES_NO3) S_RESIDUAL=RES_NO3	

!CALCULATE O2 DISTRIBUTION

CALL BC_O2()
SUBSTRATE_TYPE=5 ! S

CALL SUBSTRATE_TRANSPORT(SUBSTRATE_TYPE,MX,MY,MZ,DX,DY,DZ,UX,UY,UZ,R_O2,D_O2,DT_PHY,S_O2,RES_O2)
	IF (S_RESIDUAL<RES_O2) S_RESIDUAL=RES_O2
    
   ! PRINT*,RES_O2

END SUBROUTINE MASS_TRANSPORT_SOLVER
!============================================================================


!=========================================================================

SUBROUTINE SUBSTRATE_UPDATE()  !SUBSTRATE UPDATE AFTER CONSUMPTION
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ,S_S,S_O2,S_NH4,S_NO2,S_NO3,R_S,R_O2,R_NH4,R_NO2,R_NO3,DT_BIO
IMPLICIT NONE
INTEGER::I,J,K

!CALL REACTION_RATES(R_S,R_NH4,R_NO2,R_NO3,R_O2)


DO I=1,MX
	DO J=1,MY
		DO K=1,MZ
			S_S(I,J,K)=S_S(I,J,K)+DT_BIO*R_S(I,J,K)
			S_O2(I,J,K)=S_O2(I,J,K)+DT_BIO*R_O2(I,J,K)
			S_NH4(I,J,K)=S_NH4(I,J,K)+DT_BIO*R_NH4(I,J,K)
			S_NO2(I,J,K)=S_NO2(I,J,K)+DT_BIO*R_NO2(I,J,K)
			S_NO3(I,J,K)=S_NO3(I,J,K)+DT_BIO*R_NO3(I,J,K)
		
			IF (S_S(I,J,K)<0.D0) THEN
           !     PRINT*,'NEGATIVE S',S_S(I,J,K)
                
         !       S_S(I,J,K)=0.D0
            END IF
            
			IF (S_O2(I,J,K)<0.D0) THEN
           !     PRINT*,'NEGATIVE O2',S_O2(I,J,K)
          !      S_O2(I,J,K)=0.D0
            END IF
            
			IF (S_NH4(I,J,K)<0.D0) THEN
           !     PRINT*,'NEGATIVE NH4',S_NH4(I,J,K)
           !     S_NH4(I,J,K)=0.D0
            END IF
            
			IF (S_NO2(I,J,K)<0.D0) THEN
         !       PRINT*,'NEGATIVE NO2',R_NO2(I,J,K),I,J,K
        !        PAUSE
         !       S_NO2(I,J,K)=0.D0
            END IF
            
			IF (S_NO3(I,J,K)<0.D0) THEN
          !      PRINT*,'NEGATIVE NO3',S_NO3(I,J,K)
          !      S_NO3(I,J,K)=0.D0	
            END IF
            
		
		END DO
	END DO
END DO	

END SUBROUTINE SUBSTRATE_UPDATE




!##############################IbM SOLVER####################################


!===========================CALCULATE BIOMASS ON GRID========================

SUBROUTINE BIOMASS_ON_GRID()
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ,DX,DY,DZ,X_HET,X_AOB,X_NOB,X_EPS,X_I
USE IbM_VARIABLES,ONLY:BAC_N,BAC_M,BAC_E_D,BAC_S,BAC_X,BAC_Y,BAC_Z,BIOMASS_OCCUPANCY

IMPLICIT NONE

INTEGER::I,II,JJ,KK

X_HET=0.D0
X_AOB=0.D0
X_NOB=0.D0
X_EPS=0.D0
X_I=0.D0

BIOMASS_OCCUPANCY=0

DO I=1,BAC_N

	II=FLOOR(BAC_X(I)/DX)+1
	JJ=FLOOR(BAC_Y(I)/DY)+1
	KK=FLOOR(BAC_Z(I)/DZ)+1
   
    IF (ABS(II)>MX .OR. ABS(JJ)>MY .OR. ABS(KK)>MZ) THEN
        PRINT*,'ERROR IN BIOMASS ON GRID',I,II,JJ,KK, BAC_S(I),BAC_X(I)
        PAUSE
    END IF
    
!PRINT*,II,JJ,KK,I,BAC_X(I)
	
	IF(BAC_S(I)==1) THEN
		X_HET(II,JJ,KK)=X_HET(II,JJ,KK)+BAC_M(I)

	ELSE IF (BAC_S(I)==2) THEN
		X_AOB(II,JJ,KK)=X_AOB(II,JJ,KK)+BAC_M(I)

	ELSE IF (BAC_S(I)==3) THEN
		X_NOB(II,JJ,KK)=X_NOB(II,JJ,KK)+BAC_M(I)

	ELSE IF (BAC_S(I)==4 ) THEN
		X_EPS(II,JJ,KK)=X_EPS(II,JJ,KK)+BAC_E_D(I)

	ELSE IF (BAC_S(I)==5) THEN
		X_I(II,JJ,KK)=X_I(II,JJ,KK)+BAC_E_D(I)

	END IF

	BIOMASS_OCCUPANCY(II,JJ,KK)=1

	

END DO

X_HET=X_HET/(DX*DY*DZ)
X_AOB=X_AOB/(DX*DY*DZ)
X_NOB=X_NOB/(DX*DY*DZ)
X_EPS=X_EPS/(DX*DY*DZ)
X_I=X_I/(DX*DY*DZ)


END SUBROUTINE BIOMASS_ON_GRID

!============================================================================

SUBROUTINE SINGLE_CELL_ATTACHMENT()
USE GLOBAL_VARIABLES,ONLY:LX,LY,LZ,DX,DY,DZ,ITER_GROWTH
USE IbM_VARIABLES

IMPLICIT NONE
INTEGER::I,II,JJ,KK
REAL(8)::BAC_POLAR_R(BAC_N),R_MAX,CENTER_X,CENTER_Y,CENTER_Z,R_ATTACH, THETA_ATTACH,PHI_ATTACH,PI,X_ATTACH,Y_ATTACH,Z_ATTACH,MIN_GAP,GAP
REAL(4)::RAN

CENTER_X=FLOC_CENTER(1)  !LX/2.D0   !VERSION2 IMPROVEMNT
CENTER_Y=FLOC_CENTER(2)  !LY/2.D0
CENTER_Z=FLOC_CENTER(3)  !LZ/2.D0


!CENTER_X=LX/2.D0   !VERSION2 IMPROVEMNT
!CENTER_Y=LY/2.D0
!CENTER_Z=LZ/2.D0

PI=4.D0*DATAN(1.D0)

DO I=1,BAC_N
	BAC_POLAR_R(I)=DSQRT((BAC_X(I)-CENTER_X)**2 +(BAC_Y(I)-CENTER_Y)**2+(BAC_Z(I)-CENTER_Z)**2)
	
END DO

R_MAX=MAXVAL(BAC_POLAR_R)

R_ATTACH=R_MAX !+BAC_RA(1)*3

CALL RANDOM_SEED()

CALL RANDOM_NUMBER(RAN)
THETA_ATTACH=PI*RAN

CALL RANDOM_NUMBER(RAN)
PHI_ATTACH=2*PI*RAN

!PRINT*,'RAN=',DCOS(THETA_ATTACH)

X_ATTACH=R_ATTACH*DSIN(THETA_ATTACH)*DCOS(PHI_ATTACH)+CENTER_X
Y_ATTACH=R_ATTACH*DSIN(THETA_ATTACH)*DSIN(PHI_ATTACH)+CENTER_Y
Z_ATTACH=R_ATTACH*DCOS(THETA_ATTACH)+CENTER_Z

II=FLOOR(X_ATTACH/DX)+1
JJ=FLOOR(Y_ATTACH/DY)+1
KK=FLOOR(Z_ATTACH/DZ)+1



!PRINT*,II,JJ,KK
!PAUSE
MIN_GAP=100.D0
DO I=1,BAC_N
	
	GAP=(BAC_X(I)-X_ATTACH)**2+(BAC_Y(I)-Y_ATTACH)**2+(BAC_Z(I)-Z_ATTACH)**2
	GAP=DSQRT(GAP)

	IF (MIN_GAP>GAP) THEN
		MIN_GAP=GAP
		II=I
	END IF	

END DO

X_ATTACH=BAC_X(II)+SIGN(BAC_R(II),BAC_X(II))
Y_ATTACH=BAC_Y(II)+SIGN(BAC_R(II),BAC_Y(II))
Z_ATTACH=BAC_Z(II)+SIGN(BAC_R(II),BAC_Z(II))


!DO WHILE (BIOMASS_OCCUPANCY(II,JJ,KK)==0 .AND. R_ATTACH>DX) 

	
	
!	R_ATTACH=R_ATTACH -DX/2.D0

!	X_ATTACH=R_ATTACH*DSIN(THETA_ATTACH)*DCOS(PHI_ATTACH)+CENTER_X
!	Y_ATTACH=R_ATTACH*DSIN(THETA_ATTACH)*DSIN(PHI_ATTACH)+CENTER_Y
!	Z_ATTACH=R_ATTACH*DCOS(THETA_ATTACH)+CENTER_Z

!	II=FLOOR(X_ATTACH/DX)+1
!	JJ=FLOOR(Y_ATTACH/DY)+1
!	KK=FLOOR(Z_ATTACH/DZ)+1
!PRINT*,BIOMASS_OCCUPANCY(II,JJ,KK),R_ATTACH
!END DO
!PAUSE

!PRINT*,THETA_ATTACH,PHI_ATTACH,R_ATTACH

	ALLOCATE(BAC_M0(BAC_N))
	ALLOCATE(BAC_MSHOV0(BAC_N))
	ALLOCATE(BAC_E_D0(BAC_N))
	ALLOCATE(BAC_S0(BAC_N))
	ALLOCATE(BAC_C0(BAC_N))
	ALLOCATE(BAC_R0(BAC_N))
	ALLOCATE(BAC_RA0(BAC_N))
	ALLOCATE(BAC_X0(BAC_N))
	ALLOCATE(BAC_Y0(BAC_N))
	ALLOCATE(BAC_Z0(BAC_N))
    
    
    ALLOCATE(BAC_RATE0(BAC_N,5))
    ALLOCATE(BAC_DEAD0(BAC_N))

	BAC_M0=BAC_M
	BAC_MSHOV0=BAC_MSHOV
	BAC_E_D0=BAC_E_D
	BAC_S0=BAC_S
	BAC_C0=BAC_C
	BAC_R0=BAC_R
	BAC_RA0=BAC_RA
	BAC_X0=BAC_X
	BAC_Y0=BAC_Y
	BAC_Z0=BAC_Z
    BAC_RATE0=BAC_RATE
    BAC_DEAD0=BAC_DEAD
    

	DEALLOCATE(BAC_M)
	DEALLOCATE(BAC_MSHOV)
	DEALLOCATE(BAC_E_D)
	DEALLOCATE(BAC_S)
	DEALLOCATE(BAC_C)
	DEALLOCATE(BAC_R)
	DEALLOCATE(BAC_RA)
	DEALLOCATE(BAC_X)
	DEALLOCATE(BAC_Y)
	DEALLOCATE(BAC_Z)

    DEALLOCATE(BAC_RATE)
	DEALLOCATE(BAC_DEAD)

BAC_N=BAC_N+1


	ALLOCATE(BAC_M(BAC_N))
	ALLOCATE(BAC_MSHOV(BAC_N))
	ALLOCATE(BAC_E_D(BAC_N))
	ALLOCATE(BAC_S(BAC_N))
	ALLOCATE(BAC_C(BAC_N))
	ALLOCATE(BAC_R(BAC_N))
	ALLOCATE(BAC_RA(BAC_N))
	ALLOCATE(BAC_X(BAC_N))
	ALLOCATE(BAC_Y(BAC_N))
	ALLOCATE(BAC_Z(BAC_N))
    
    ALLOCATE(BAC_RATE(BAC_N,5))
    ALLOCATE(BAC_DEAD(BAC_N))
!PRINT*,BAC_S

!PAUSE
    
BAC_DEAD=0

BAC_M(1:BAC_N-1)=BAC_M0(1:BAC_N-1)
BAC_MSHOV(1:BAC_N-1)=BAC_MSHOV0(1:BAC_N-1)
BAC_E_D(1:BAC_N-1)=BAC_E_D0(1:BAC_N-1)
BAC_S(1:BAC_N-1)=BAC_S0(1:BAC_N-1)
BAC_C(1:BAC_N-1)=BAC_C0(1:BAC_N-1)
BAC_X(1:BAC_N-1)=BAC_X0(1:BAC_N-1)
BAC_Y(1:BAC_N-1)=BAC_Y0(1:BAC_N-1)
BAC_Z(1:BAC_N-1)=BAC_Z0(1:BAC_N-1)


!   VERSION2 IMPROVEMENT
BAC_R(1:BAC_N-1)=BAC_R0(1:BAC_N-1)
BAC_RA(1:BAC_N-1)=BAC_RA0(1:BAC_N-1)

BAC_RATE(1:BAC_N-1,:)=BAC_RATE0(1:BAC_N-1,:)
BAC_RATE(BAC_N,:)=0.D0
BAC_DEAD(1:BAC_N-1)=BAC_DEAD0(1:BAC_N-1)
!PAUSE

! NEW CELL ATTACHMENT

BAC_X(BAC_N)=X_ATTACH
BAC_Y(BAC_N)=Y_ATTACH
BAC_Z(BAC_N)=Z_ATTACH

CALL RANDOM_NUMBER(RAN)

IF (RAN<=0.6D0) THEN
	BAC_S(BAC_N)=1
	BAC_C(BAC_N)=0
	BAC_M(BAC_N)=MASS_HET
	BAC_E_D(BAC_N)=MASS_EPS

	N_HET=N_HET+1

ELSE IF (RAN>0.6D0 .AND. RAN<=0.8D0) THEN
	BAC_S(BAC_N)=2
	BAC_C(BAC_N)=MAXVAL(BAC_C0)+1
	BAC_M(BAC_N)=MASS_AOB
	BAC_E_D(BAC_N)=0.D0

	N_AOB=N_AOB+1
	N_COLONY_AOB=N_COLONY_AOB+1

ELSE
	BAC_S(BAC_N)=3
	BAC_C(BAC_N)=MAXVAL(BAC_C0)+1
	BAC_M(BAC_N)=MASS_NOB
	BAC_E_D(BAC_N)=0.D0

	N_NOB=N_NOB+1
	N_COLONY_NOB=N_COLONY_NOB+1

!	PRINT*,(BAC_C)

!	PAUSE
END IF


!   VERSION2 IMPROVEMENT

BAC_R(BAC_N)=((BAC_M(BAC_N)/BAC_RHO+BAC_E_D(BAC_N)/BAC_RHOE)*3/(4*PI))**(1.D0/3.D0)
BAC_RA(BAC_N)=((BAC_M(BAC_N)/BAC_RHO)*3/(4*PI))**(1.D0/3.D0)



	DEALLOCATE(BAC_M0)
	DEALLOCATE(BAC_MSHOV0)
	DEALLOCATE(BAC_E_D0)
	DEALLOCATE(BAC_S0)
	DEALLOCATE(BAC_C0)
	DEALLOCATE(BAC_R0)
	DEALLOCATE(BAC_RA0)
	DEALLOCATE(BAC_X0)
	DEALLOCATE(BAC_Y0)
	DEALLOCATE(BAC_Z0)

    DEALLOCATE(BAC_RATE0)
    DEALLOCATE(BAC_DEAD0)
!PRINT*,BAC_C,BAC_S

!PAUSE

    END SUBROUTINE SINGLE_CELL_ATTACHMENT

!=====================GROWTH=================================================
    
SUBROUTINE GROWTH()
USE GLOBAL_VARIABLES
USE IbM_VARIABLES
USE REACTOR_VARIABLES

IMPLICIT NONE
INTEGER,ALLOCATABLE::IND_HET(:),IND_AOB(:),IND_NOB(:),IND_EPS(:),IND_INERT0(:),IND_INERT(:)
INTEGER::I,J,K,II,JJ,KK,I_HET,I_AOB,I_NOB,I_EPS,I_INERT,DECAY_INDEX,BAC_N_OLD,BAC_N_NEW,NN
REAL(8)::VAR1,VAR2,VAR3,VAR4,TERM1,TERM2,TERM3,TERM4,GR_HET_O2,GR_HET_NO3,GR_HET_NO2,DR_HET,GR_AOB_O2,DR_AOB,GR_NOB_O2,DR_NOB,DR_EPS
REAL(8)::R_DECAY_HET,R_DECAY_AOB,R_DECAY_NOB,M_SUBSTRATE,PI,THETA,PHI,FRACTION
REAL(4)::RAN


REAL(8),ALLOCATABLE::BAC_X_OLD(:),BAC_Y_OLD(:),BAC_Z_OLD(:),BAC_M_OLD(:),BAC_E_D_OLD(:),BAC_R_OLD(:),BAC_RA_OLD(:),BAC_MSHOV_OLD(:),BAC_RATE_OLD(:,:)
REAL(8),ALLOCATABLE::BAC_X_NEW(:),BAC_Y_NEW(:),BAC_Z_NEW(:),BAC_M_NEW(:),BAC_E_D_NEW(:),BAC_R_NEW(:),BAC_RA_NEW(:),BAC_MSHOV_NEW(:)
INTEGER,ALLOCATABLE::BAC_S_OLD(:),BAC_C_OLD(:),BAC_S_NEW(:),BAC_C_NEW(:),BAC_DEAD_OLD(:)



PI=4.D0*DATAN(1.D0)

!FIND GROWTH AND DECAY RATES OF HET, AOB,NOB, EPS

!PRINT*,'N_HET====',BAC_C
!PAUSE

! VARIABLES TO SAVE OLD DATA
ALLOCATE(BAC_X_OLD(BAC_N))
ALLOCATE(BAC_Y_OLD(BAC_N))
ALLOCATE(BAC_Z_OLD(BAC_N))
ALLOCATE(BAC_M_OLD(BAC_N))
ALLOCATE(BAC_E_D_OLD(BAC_N))
ALLOCATE(BAC_R_OLD(BAC_N))
ALLOCATE(BAC_RA_OLD(BAC_N))
ALLOCATE(BAC_MSHOV_OLD(BAC_N))
ALLOCATE(BAC_S_OLD(BAC_N))
ALLOCATE(BAC_C_OLD(BAC_N))

ALLOCATE(BAC_DEAD_OLD(BAC_N))

!VARIABLES FOR NEW PARTICLES
NN=5000  !MAXIMUM NUMBER OF NEW PARTICLES WHICH CAN GENERATE IN ONE TIME STEP

ALLOCATE(BAC_X_NEW(NN))
ALLOCATE(BAC_Y_NEW(NN))
ALLOCATE(BAC_Z_NEW(NN))
ALLOCATE(BAC_M_NEW(NN))
ALLOCATE(BAC_E_D_NEW(NN))
ALLOCATE(BAC_R_NEW(NN))
ALLOCATE(BAC_RA_NEW(NN))
ALLOCATE(BAC_MSHOV_NEW(NN))
ALLOCATE(BAC_S_NEW(NN))
ALLOCATE(BAC_C_NEW(NN))



!INDICES OF PARTICLES
ALLOCATE(IND_HET(N_HET))
ALLOCATE(IND_AOB(N_AOB))
ALLOCATE(IND_NOB(N_NOB))
ALLOCATE(IND_EPS(N_EPS))
ALLOCATE(IND_INERT(N_INERT))

ALLOCATE(IND_INERT0(BAC_N))

!REACTION RATES
ALLOCATE(RX(BAC_N))     !GROWTH RATES FOR HET,AOB,NOB
ALLOCATE(RD(BAC_N))     !DECAY RATES FOR HET,AOB,NOB,EPS     
ALLOCATE(RE(BAC_N))     !GROWTH RATE FOR EPS



I_HET=0
I_AOB=0
I_NOB=0
I_EPS=0
I_INERT=0

RX=0.D0
RE=0.D0
RD=0.D0

!PRINT*,SIZE(BAC_M)

!PAUSE
!PAUSE


!PRINT*,'TEST1==========',BAC_DEAD
!PAUSE


!GROWTH/DECAY RATES AND INDICES OF PARTICLES

BAC_N_PREVIOUS=BAC_N

!DEALLOCATE(BAC_RATE)
!ALLOCATE(BAC_RATE(BAC_N,5))
ALLOCATE(BAC_RATE_OLD(BAC_N,5))
BAC_RATE(:,:)=0.D0
BAC_RATE_OLD(:,:)=0.D0

DO I=1,BAC_N


!	PRINT*,I,BAC_S(I)

	II=FLOOR(BAC_X(I)/DX)+1
	JJ=FLOOR(BAC_Y(I)/DY)+1
	KK=FLOOR(BAC_Z(I)/DZ)+1

!	PRINT*,II,JJ,KK
    
    IF (ABS(II)>MX .OR. ABS(JJ)>MY .OR. ABS(KK)>MZ) THEN
        PRINT*,'ERROR IN GROWTH',I,II,JJ,KK, BAC_S(I),BAC_X(I)
        PAUSE
    END IF

	SELECT CASE (BAC_S(I))

		CASE(1)		!HET

	!		PRINT*,I

			!GR_HET_O2(MU_M_HET,K_S_HET,K_O2_HET,S_S,S_O2,X_HET)
			!GR_HET_NO3(ETA_H,MU_M_HET,K_S_HET,K_NO3_HET,K_O2_HET,S_S,S_NO3,S_O2,X_HET)
			!GR_HET_NO2(ETA_H,MU_M_HET,K_S_HET,K_NO2_HET,K_O2_HET,S_S,S_NO2,S_O2,X_HET)

			VAR1=S_S(II,JJ,KK)
			VAR2=S_O2(II,JJ,KK)
			VAR3=BAC_M(I)
			
			!TERM1=GR_HET_O2(MU_M_HET,K_S_HET,K_O2_HET,S_S,S_O2,X_HET)
		
			TERM1=GR_HET_O2(MU_M_HET,K_S_HET,K_O2_HET,VAR1,VAR2,VAR3)  !AEROBIC GROWTH OF HET ON O2
            
            BAC_RATE(I,2)=TERM1*(1.D0-Y_HET-Y_EPS)/Y_HET  !O2 CONSUMPTION BY HET

		!	PRINT*,'HET RATE===============',I,VAR1,VAR2,VAR3
         !   PAUSE
			
			VAR1=S_S(II,JJ,KK)
			VAR2=S_NO3(II,JJ,KK)
			VAR3=S_O2(II,JJ,KK)
			VAR4=BAC_M(I)

			!TERM2=GR_HET_NO3(ETA_H,MU_M_HET,K_S_HET,K_NO3_HET,K_O2_HET,S_S,S_NO3,S_O2,X_HET)
		
			TERM2=GR_HET_NO3(ETA_H,MU_M_HET,K_S_HET,K_NO3_HET,K_O2_HET,VAR1,VAR2,VAR3,VAR4) !ANOXIC GROWTH OF HET ON NO3

            BAC_RATE(I,5)=TERM2*(1.D0-Y_HET-Y_EPS)/(2.86D0*Y_HET)       !NO3 CONSUMPTION BY HET
            
			VAR1=S_S(II,JJ,KK)
			VAR2=S_NO2(II,JJ,KK)
			VAR3=S_O2(II,JJ,KK)
			VAR4=BAC_M(I)
			
			!TERM3=GR_HET_NO2(ETA_H,MU_M_HET,K_S_HET,K_NO2_HET,K_O2_HET,S_S,S_NO2,S_O2,X_HET)

			TERM3=GR_HET_NO2(ETA_H,MU_M_HET,K_S_HET,K_NO2_HET,K_O2_HET,VAR1,VAR2,VAR3,VAR4)  !ANOXIC GROWTH OF HET ON NO2
	
			BAC_RATE(I,4)=TERM3*(1.D0-Y_HET-Y_EPS)/(1.71D0*Y_HET)       !NO2 CONSUMPTION BY HET
			
            RX(I)=TERM1+TERM2+TERM3  !GROWTH RATE OF HET

			
	
			RE(I)=(Y_EPS/Y_HET)*RX(I) !EPS GROWTH RATE
            
            BAC_RATE(I,1)=(1.D0/Y_HET)*RX(I)   !S CONSUMPTION BY HET
			
			!DR_HET(B_HET,X_HET)

			VAR1=BAC_M(I)
			
			RD(I)=DR_HET(B_HET,VAR1) !DECAY RATE OF HET
			
			
			I_HET=I_HET+1

			IF(I_HET>N_HET) THEN
				PRINT*,'INDEX ERROR IN GROWTH SUB1',I_HET,N_HET
				PAUSE
			END IF
			
			IND_HET(I_HET)=I	
	
		CASE(2) !AOB

			!GR_AOB_O2(MU_M_AOB,K_NH4_AOB,K_O2_AOB,S_NH4,S_O2,X_AOB)

			VAR1=S_NH4(II,JJ,KK)
			VAR2=S_O2(II,JJ,KK)
			VAR3=BAC_M(I)

			!TERM1=GR_AOB_O2(MU_M_AOB,K_NH4_AOB,K_O2_AOB,S_NH4,S_O2,X_AOB)

			TERM1=GR_AOB_O2(MU_M_AOB,K_NH4_AOB,K_O2_AOB,VAR1,VAR2,VAR3) !AEROBIC GROWTH OF AOB

            BAC_RATE(I,2)=TERM1*(3.42-Y_AOB)/Y_AOB      !O2 CONSUMPTION BY AOB
            BAC_RATE(I,3)=TERM1*(1.D0/Y_AOB)    !NH4 CONSUMPTION BY AOB
            BAC_RATE(I,4)=TERM1*(1.D0/Y_AOB)    !NO2 PRODUCTION BY AOB
            
			RX(I)=TERM1

			!DR_AOB(B_AOB,X_AOB)

			VAR1=BAC_M(I)
		
			RD(I)=DR_AOB(B_AOB,VAR1)

			I_AOB=I_AOB+1

			IF(I_AOB>N_AOB) THEN
				PRINT*,'INDEX ERROR IN GROWTH SUB2'
				PAUSE
			END IF
			
			IND_AOB(I_AOB)=I

		CASE(3) !NOB

			!GR_NOB_O2(MU_M_NOB,K_NO2_NOB,K_O2_NOB,S_NO2,S_O2,X_NOB)

			
			
			VAR1=S_NO2(II,JJ,KK)
			VAR2=S_O2(II,JJ,KK)
			VAR3=BAC_M(I)
			
	!		PRINT*,I

			!TERM1=GR_NOB_O2(MU_M_NOB,K_NO2_NOB,K_O2_NOB,S_NO2,S_O2,X_NOB)
			TERM1=GR_NOB_O2(MU_M_NOB,K_NO2_NOB,K_O2_NOB,VAR1,VAR2,VAR3)  !AEROBIC GROWTH OF NOB

            BAC_RATE(I,2)=TERM1*(1.15-Y_NOB)/Y_NOB      !O2 CONSUMPTION BY NOB
            BAC_RATE(I,4)=TERM1*(1.D0/Y_NOB)    !NO2 CONSUMPTION BY NOB
            BAC_RATE(I,5)=TERM1*(1.D0/Y_NOB)    !NO3 PRODUCTION BY NOB
            
			RX(I)=TERM1
         !   PRINT*,'NOB NO2 UPTAKE RATE',TERM1
			!DR_NOB(B_NOB,X_NOB)

			VAR1=BAC_M(I)
		
			RD(I)=DR_NOB(B_NOB,VAR1)

			I_NOB=I_NOB+1

			IF(I_NOB>N_NOB) THEN
				PRINT*,'INDEX ERROR IN GROWTH SUB3'
				PAUSE
			END IF
			
			IND_NOB(I_NOB)=I

		CASE(4) !EPS
			
			!DR_EPS(B_EPS,X_EPS)

			IF (BAC_E_D(I)>0.D0) THEN
			
			
			VAR1=BAC_E_D(I)
		
			RD(I)=DR_EPS(B_EPS,VAR1)

			I_EPS=I_EPS+1

			IF(I_EPS>N_EPS) THEN
				PRINT*,'INDEX ERROR IN GROWTH SUB4'
				PAUSE
			END IF
			
			IND_EPS(I_EPS)=I
            
         !   BAC_E_D(I)=BAC_E_D(I)-DT_BIO*DR_EPS(B_EPS,VAR1)
            
            IF (BAC_E_D(I)>DT_BIO*DR_EPS(B_EPS,VAR1)) THEN
            
                S_S(II,JJ,KK)=S_S(II,JJ,KK)+ DT_BIO*DR_EPS(B_EPS,VAR1)/(DX*DY*DZ)   !VERSION2 IMPROVEMENTS, DECAYED EPS CONTRIBUTION TO S
                BAC_E_D(I)=BAC_E_D(I)-DT_BIO*DR_EPS(B_EPS,VAR1)
                BAC_RATE(I,1)=DR_EPS(B_EPS,VAR1)
            ELSE IF (BAC_E_D(I)<=DT_BIO*DR_EPS(B_EPS,VAR1)) THEN
                S_S(II,JJ,KK)=S_S(II,JJ,KK)+BAC_E_D(I)/(DX*DY*DZ)      
                
                BAC_RATE(I,1)=BAC_E_D(I)/DT_BIO 
            

			!ELIMINATE DISSOLVED EPS PARTICLES

			    BAC_S(I)=0
			    BAC_M(I)=0.D0
			    BAC_E_D(I)=0.D0
			    BAC_C(I)=0
			    BAC_R(I)=0.D0
			    BAC_RA(I)=0.D0



			    N_EPS=N_EPS-1
                N_EPS_DISSOLVED=N_EPS_DISSOLVED+1

			END IF
        END IF

		CASE(5) !INERT

			

			I_INERT=I_INERT+1

	!		PRINT*,'INNERT',I_INERT,N_INERT
			
			IF(I_INERT>N_INERT) THEN
				PRINT*,'INDEX ERROR IN GROWTH SUB5',I_INERT,N_INERT
				PAUSE
			END IF	


			IND_INERT0(I_INERT)=I

		

	
	END SELECT

	

END DO

!PRINT*,'TEST2=======',BAC_E_D


!PAUSE

IND_INERT(1:N_INERT)=IND_INERT0(1:N_INERT)


!FIND VIRTUAL DECAY MASS FOR EACH SPECIES


R_DECAY_HET=SUM(RD(IND_HET))
R_DECAY_AOB=SUM(RD(IND_AOB))
R_DECAY_NOB=SUM(RD(IND_NOB))

!PRINT*,'@@@@@',M_DECAY_HET
!PAUSE

M_DECAY_HET=M_DECAY_HET+R_DECAY_HET*DT_BIO !VIRTUAL DECAY MASS OF HET
M_DECAY_AOB=M_DECAY_AOB+R_DECAY_AOB*DT_BIO !VIRTUAL DECAY MASS OF AOB
M_DECAY_NOB=M_DECAY_NOB+R_DECAY_NOB*DT_BIO !VIRTUAL DECAY MASS OF NOB

M_SUBSTRATE=SUM(RD(IND_EPS))*DT_BIO  !CARBON MASS PRODUCED DUE TO EPS DESOLVING

BAC_E_D(IND_EPS)=BAC_E_D(IND_EPS)-RD(IND_EPS)*DT_BIO

!PRINT*,'TEST3======',BAC_E_D
!PAUSE
 CALL RANDOM_SEED()
! DIE HET
IF (M_DECAY_HET>2*MASS_HET) THEN    !VERSION2 IMPROVEMNTS

	DO WHILE (M_DECAY_HET>2*MASS_HET .AND. N_HET>5)
       
		CALL RANDOM_NUMBER(RAN)
		
		DECAY_INDEX=FLOOR(RAN*N_HET)
		IF(DECAY_INDEX<1) DECAY_INDEX=1

		IF (BAC_S(IND_HET(DECAY_INDEX))==1) THEN

!		PRINT*,RAN*N_HET,RAN

	!	PRINT*,'HET DIE',FLOOR(RAN*N_HET)

	!	PAUSE

		M_DECAY_HET=M_DECAY_HET-BAC_M(IND_HET(DECAY_INDEX))

		M_SUBSTRATE=M_SUBSTRATE+BAC_M(IND_HET(DECAY_INDEX))*(1.D0-Y_I)
		
		M_SUBSTRATE=M_SUBSTRATE+BAC_E_D(IND_HET(DECAY_INDEX))

		BAC_E_D(IND_HET(DECAY_INDEX))=BAC_M(IND_HET(DECAY_INDEX))*Y_I

        II=FLOOR(BAC_X(IND_HET(DECAY_INDEX))/DX)+1             !VERSION2 IMPROVEMENTS
	    JJ=FLOOR(BAC_Y(IND_HET(DECAY_INDEX))/DY)+1
	    KK=FLOOR(BAC_Z(IND_HET(DECAY_INDEX))/DZ)+1

        S_S(II,JJ,KK)=S_S(II,JJ,KK)+(BAC_M(IND_HET(DECAY_INDEX))*(1.D0-Y_I)+BAC_E_D(IND_HET(DECAY_INDEX)))/(DX*DY*DZ)
        BAC_RATE(IND_HET(DECAY_INDEX),1)=(BAC_M(IND_HET(DECAY_INDEX))*(1.D0-Y_I)+BAC_E_D(IND_HET(DECAY_INDEX)))/DT_BIO
        
		BAC_M(IND_HET(DECAY_INDEX))=0.D0
		RX(IND_HET(DECAY_INDEX))=0.D0
		BAC_S(IND_HET(DECAY_INDEX))=5
		BAC_C(IND_HET(DECAY_INDEX))=0
        
		N_HET=N_HET-1

		N_INERT=N_INERT+1
        BAC_DEAD(IND_HET(DECAY_INDEX))=1
        
        
        IND_INERT0(N_INERT)=IND_HET(DECAY_INDEX)
		END IF
	END DO

END IF

!PAUSE

!DIE AOB
!PRINT*,'TEST4======',BAC_C
!PAUSE

IF (M_DECAY_AOB>2*MASS_AOB ) THEN   !VERSION2 IMPROVEMNTS

	DO WHILE (M_DECAY_AOB>2*MASS_AOB .AND. N_AOB>5)

	
		CALL RANDOM_NUMBER(RAN)
		
		DECAY_INDEX=FLOOR(RAN*N_AOB)
		IF(DECAY_INDEX<1) DECAY_INDEX=1

		IF (BAC_S(IND_AOB(DECAY_INDEX))==2) THEN

		M_DECAY_AOB=M_DECAY_AOB-BAC_M(IND_AOB(DECAY_INDEX))

		M_SUBSTRATE=M_SUBSTRATE+BAC_M(IND_AOB(DECAY_INDEX))*(1.D0-Y_I)
		
		BAC_E_D(IND_AOB(DECAY_INDEX))=BAC_M(IND_AOB(DECAY_INDEX))*Y_I

        II=FLOOR(BAC_X(IND_AOB(DECAY_INDEX))/DX)+1             !VERSION2 IMPROVEMENTS
	    JJ=FLOOR(BAC_Y(IND_AOB(DECAY_INDEX))/DY)+1
	    KK=FLOOR(BAC_Z(IND_AOB(DECAY_INDEX))/DZ)+1

        S_S(II,JJ,KK)=S_S(II,JJ,KK)+(BAC_M(IND_AOB(DECAY_INDEX))*(1.D0-Y_I))/(DX*DY*DZ)
        BAC_RATE(IND_AOB(DECAY_INDEX),1)=(BAC_M(IND_AOB(DECAY_INDEX))*(1.D0-Y_I))/DT_BIO
        
		BAC_M(IND_AOB(DECAY_INDEX))=0.D0
		RX(IND_AOB(DECAY_INDEX))=0.D0
		BAC_S(IND_AOB(DECAY_INDEX))=5
        BAC_C(IND_AOB(DECAY_INDEX))=0
        
		N_AOB=N_AOB-1
		N_INERT=N_INERT+1
        BAC_DEAD(IND_AOB(DECAY_INDEX))=2
        IND_INERT0(N_INERT)=IND_AOB(DECAY_INDEX)
		END IF

	END DO

END IF

!PRINT*,'TEST5======',M_DECAY_HET

!DIE NOB


IF (M_DECAY_NOB>2*MASS_NOB ) THEN   !VERSION2 IMPROVEMENTS

	DO WHILE (M_DECAY_NOB>2*MASS_NOB.AND. N_NOB>5)
        CALL RANDOM_NUMBER(RAN)
		
		DECAY_INDEX=FLOOR(RAN*N_NOB)

	IF(DECAY_INDEX<1) DECAY_INDEX=1

		IF (BAC_S(IND_NOB(DECAY_INDEX))==3) THEN

		M_DECAY_NOB=M_DECAY_NOB-BAC_M(IND_NOB(DECAY_INDEX))

		M_SUBSTRATE=M_SUBSTRATE+BAC_M(IND_NOB(DECAY_INDEX))*(1.D0-Y_I)
		
		BAC_E_D(IND_NOB(DECAY_INDEX))=BAC_M(IND_NOB(DECAY_INDEX))*Y_I

        II=FLOOR(BAC_X(IND_NOB(DECAY_INDEX))/DX)+1             !VERSION2 IMPROVEMENTS
	    JJ=FLOOR(BAC_Y(IND_NOB(DECAY_INDEX))/DY)+1
	    KK=FLOOR(BAC_Z(IND_NOB(DECAY_INDEX))/DZ)+1

        S_S(II,JJ,KK)=S_S(II,JJ,KK)+(BAC_M(IND_NOB(DECAY_INDEX))*(1.D0-Y_I))/(DX*DY*DZ)
        BAC_RATE(IND_NOB(DECAY_INDEX),1)=(BAC_M(IND_NOB(DECAY_INDEX))*(1.D0-Y_I))/DT_BIO
        
		BAC_M(IND_NOB(DECAY_INDEX))=0.D0
		RX(IND_NOB(DECAY_INDEX))=0.D0
		BAC_S(IND_NOB(DECAY_INDEX))=5
		BAC_C(IND_NOB(DECAY_INDEX))=0
        
		N_NOB=N_NOB-1
		N_INERT=N_INERT+1
        BAC_DEAD(IND_NOB(DECAY_INDEX))=3
        IND_INERT0(N_INERT)=IND_NOB(DECAY_INDEX)
		END IF

	END DO

END IF

DEALLOCATE(IND_INERT)

ALLOCATE(IND_INERT(N_INERT))

IND_INERT(1:N_INERT)=IND_INERT0(1:N_INERT)


!PAUSE

!PRINT*,'TEST6========',BAC_C
!PAUSE

!VERSION2 IMPROVEMENTS*******************************
IF (BIOREACTOR==1 .AND. MASS_TRANSFER==1) THEN

    NFLOCS=NFLOCS*(1.D0-DT_BIO/SRT)

    S_S_R=S_S_R+M_SUBSTRATE*NFLOCS/V_R
ELSE IF (MASS_TRANSFER==1) THEN
 !   S_S(:,:,:)=S_S(:,:,:)+M_SUBSTRATE/(LX*LY*LZ)       !VERSION2 IMPROVEMENTS
END IF
!VERSION2 IMPROVEMENTS*******************************

!PRINT*,R_O2

!PAUSE


!BIOMASS & SIZE UPDATE-EULER METHOD

BAC_M=BAC_M+RX*DT_BIO
BAC_E_D=BAC_E_D+RE*DT_BIO

!BAC_M=BAC_M+RX*DT_BIO

!UPDATE RADIUS OF PARTICLES=============================
BAC_RA=((BAC_M/BAC_RHO)*3/(4*PI))**(1.D0/3.D0)
BAC_R=((BAC_M/BAC_RHO+BAC_E_D/BAC_RHOE)*3/(4*PI))**(1.D0/3.D0)
BAC_R(IND_INERT)=((BAC_E_D(IND_INERT)/BAC_RHOD)*3/(4*PI))**(1.D0/3.D0) 

!PRINT*,'============CELL MASS======================'

!PRINT*,BAC_M(2),RX(2)


!PRINT*,'==========================================='



!PRINT*,N_HET,BAC_S


DEALLOCATE(RX)
DEALLOCATE(RD)
DEALLOCATE(RE)  

!PRINT*,'TEST=========7',BAC_DEAD_OLD
!PAUSE

!DIVISION

BAC_N_OLD=BAC_N
BAC_N_NEW=0    !NUMBER OF NEW CELLS ADDED TO THE FLOC

DO I=1,BAC_N_OLD


!PRINT*,I	
	

!EXCRETION OF EPS

	IF (BAC_S(I)==1 .AND. BAC_R(I)>BAC_RA(I)*1.30D0) THEN     !EPS EXCRETION CRITERION

!	PRINT*,'NEW EPS'
	
!	PAUSE

	
		CALL RANDOM_NUMBER(RAN)
		THETA=PI*RAN

		
		CALL RANDOM_NUMBER(RAN)
		PHI=2*PI*RAN

		N_EPS=N_EPS+1

		BAC_N=BAC_N+1

		BAC_N_NEW=BAC_N_NEW+1

		IF (BAC_N_NEW>NN) THEN

			PRINT*,'ERROR IN DIVISION1, TOO MANY NEW CELLS'
			PAUSE
		END IF

	!	BAC_X_NEW(BAC_N_NEW)=BAC_X(I)+2*BAC_R(I)*DSIN(THETA)*DCOS(PHI)
	!	BAC_Y_NEW(BAC_N_NEW)=BAC_Y(I)+2*BAC_R(I)*DSIN(THETA)*DSIN(PHI)
	!	BAC_Z_NEW(BAC_N_NEW)=BAC_Z(I)+2*BAC_R(I)*DCOS(THETA)


!		PRINT*,'====',BAC_X_NEW(BAC_N_NEW),BAC_X(I),BAC_R(I),I

		BAC_S_NEW(BAC_N_NEW)=4  !NEW EPS
		BAC_C_NEW(BAC_N_NEW)=BAC_C(I)   !NEW EPS

        IF (BAC_C(I) .NE. 0) THEN
            PRINT*,'ERROR IN EPS EXCRETION'
            PAUSE
        END IF
                
		FRACTION=DIVISION_FRACTION+0.2D0*(RAN-0.5D0)
       ! PRINT*,FRACTION
       ! PAUSE
		BAC_M_NEW(BAC_N_NEW)=0.D0  !NEW EPS
		BAC_E_D_NEW(BAC_N_NEW)=FRACTION*BAC_E_D(I) !NEW EPS
		BAC_RA_NEW(BAC_N_NEW)=0.D0 !NEW EPS

		BAC_R_NEW(BAC_N_NEW)=((BAC_E_D_NEW(BAC_N_NEW)/BAC_RHOE)*3/(4*PI))**(1.D0/3.D0) !NEW EPS

		BAC_MSHOV_NEW(BAC_N_NEW)=BAC_M_NEW(BAC_N_NEW)+BAC_E_D_NEW(BAC_N_NEW) !NEW EPS


		BAC_E_D(I)=BAC_E_D(I)-BAC_E_D_NEW(BAC_N_NEW) !UPDATE ORIGINAL HET

		BAC_R(I)=((BAC_M(I)/BAC_RHO+BAC_E_D(I)/BAC_RHOE)*3/(4*PI))**(1.D0/3.D0) !UPDATE ORIGINAL HET

	    ! VERSION2 IMPROVEMENTS
	    BAC_X_NEW(BAC_N_NEW)=BAC_X(I)+(BAC_R(I)+BAC_R_NEW(BAC_N_NEW))*DSIN(THETA)*DCOS(PHI) !NEW EPS
		BAC_Y_NEW(BAC_N_NEW)=BAC_Y(I)+(BAC_R(I)+BAC_R_NEW(BAC_N_NEW))*DSIN(THETA)*DSIN(PHI) !NEW EPS
		BAC_Z_NEW(BAC_N_NEW)=BAC_Z(I)+(BAC_R(I)+BAC_R_NEW(BAC_N_NEW))*DCOS(THETA)           !NEW EPS
    
    
    END IF




!	HET, AOB, NOB DIVISION===================

	IF ( (BAC_S(I)==1 .AND. BAC_M(I)>BAC_MMAX(1)) .OR. (BAC_S(I)==2 .AND. BAC_M(I)>BAC_MMAX(2)).OR. (BAC_S(I)==3 .AND. BAC_M(I)>BAC_MMAX(3)) ) THEN  !CRITERIA FOR DIVISION


		SELECT CASE (BAC_S(I))
			
				CASE(1)
					N_HET=N_HET+1
	
				CASE(2)
					N_AOB=N_AOB+1
                    
				CASE(3)
					N_NOB=N_NOB+1
		END SELECT
		 
		
	!	PRINT*,'NEW HET,AOB,NOB'
		
	!	PAUSE
		
		CALL RANDOM_NUMBER(RAN)
		THETA=PI*RAN

		
		CALL RANDOM_NUMBER(RAN)
		PHI=2*PI*RAN

		BAC_N=BAC_N+1

		BAC_N_NEW=BAC_N_NEW+1

		IF (BAC_N_NEW>NN) THEN

			PRINT*,'ERROR IN DIVISION2, TOO MANY NEW CELLS'
			PAUSE
		END IF

	!	BAC_X_NEW(BAC_N_NEW)=BAC_X(I)+1*BAC_R(I)*DSIN(THETA)*DCOS(PHI)
	!	BAC_Y_NEW(BAC_N_NEW)=BAC_Y(I)+1*BAC_R(I)*DSIN(THETA)*DSIN(PHI)
	!	BAC_Z_NEW(BAC_N_NEW)=BAC_Z(I)+1*BAC_R(I)*DCOS(THETA)

		BAC_S_NEW(BAC_N_NEW)=BAC_S(I)  !NEW CELL
		BAC_C_NEW(BAC_N_NEW)=BAC_C(I)

		FRACTION=DIVISION_FRACTION+0.2D0*(RAN-0.5D0)

		BAC_M_NEW(BAC_N_NEW)=FRACTION*BAC_M(I)
		BAC_E_D_NEW(BAC_N_NEW)=FRACTION*BAC_E_D(I)
		
		BAC_RA_NEW(BAC_N_NEW)=((BAC_M_NEW(BAC_N_NEW)/BAC_RHO)*3/(4*PI))**(1.D0/3.D0)

		BAC_R_NEW(BAC_N_NEW)=((BAC_M_NEW(BAC_N_NEW)/BAC_RHO+BAC_E_D_NEW(BAC_N_NEW)/BAC_RHOE)*3/(4*PI))**(1.D0/3.D0)	

		BAC_MSHOV_NEW(BAC_N_NEW)=BAC_M_NEW(BAC_N_NEW)+BAC_E_D_NEW(BAC_N_NEW)
		
	!	BAC_X(I)=BAC_X(I)-1*BAC_R(I)*DSIN(THETA)*DCOS(PHI)
	!	BAC_Y(I)=BAC_Y(I)-1*BAC_R(I)*DSIN(THETA)*DSIN(PHI)
	!	BAC_Z(I)=BAC_Z(I)-1*BAC_R(I)*DCOS(THETA)

		BAC_M(I)=BAC_M(I)-BAC_M_NEW(BAC_N_NEW) !ORIGINAL CELL
		BAC_E_D(I)=BAC_E_D(I)-BAC_E_D_NEW(BAC_N_NEW)

		BAC_RA(I)=((BAC_M(I)/BAC_RHO)*3/(4*PI))**(1.D0/3.D0)
		BAC_R(I)=((BAC_M(I)/BAC_RHO+BAC_E_D(I)/BAC_RHOE)*3/(4*PI))**(1.D0/3.D0)

		BAC_MSHOV(I)=BAC_M(I)+BAC_E_D(I)
        
        !VERSION2 IMPROVEMENTS*************
        
        BAC_X_NEW(BAC_N_NEW)=BAC_X(I)+1*BAC_R_NEW(BAC_N_NEW)*DSIN(THETA)*DCOS(PHI)
		BAC_Y_NEW(BAC_N_NEW)=BAC_Y(I)+1*BAC_R_NEW(BAC_N_NEW)*DSIN(THETA)*DSIN(PHI)
		BAC_Z_NEW(BAC_N_NEW)=BAC_Z(I)+1*BAC_R_NEW(BAC_N_NEW)*DCOS(THETA)
	
	    BAC_X(I)=BAC_X(I)-1*BAC_R(I)*DSIN(THETA)*DCOS(PHI)
		BAC_Y(I)=BAC_Y(I)-1*BAC_R(I)*DSIN(THETA)*DSIN(PHI)
		BAC_Z(I)=BAC_Z(I)-1*BAC_R(I)*DCOS(THETA)
      
        !VERSION2 IMPROVEMENTS*************
        
	END IF

	
	BAC_X_OLD(I)=BAC_X(I)  !STORE OLD DATA
	BAC_Y_OLD(I)=BAC_Y(I)
	BAC_Z_OLD(I)=BAC_Z(I)
	
	
	BAC_M_OLD(I)=BAC_M(I)
	BAC_E_D_OLD(I)=BAC_E_D(I)
	BAC_S_OLD(I)=BAC_S(I)
	BAC_C_OLD(I)=BAC_C(I)
	
	BAC_R_OLD(I)=BAC_R(I)
	BAC_RA_OLD(I)=BAC_RA(I)

	BAC_MSHOV_OLD(I)=BAC_MSHOV(I)
!		PRINT*,I,BAC_N_NEW
    BAC_DEAD_OLD(I)=BAC_DEAD(I)
END DO

BAC_RATE_OLD=BAC_RATE !STORE OLD DATA

!BAC_DEAD_OLD=BAC_DEAD
!PRINT*,'TEST8=====',BAC_DEAD_OLD

!PAUSE

IF (BAC_N_NEW>0) THEN

!PRINT*,'COLONY=', BAC_C
!PAUSE

DEALLOCATE(BAC_X)
DEALLOCATE(BAC_Y)
DEALLOCATE(BAC_Z)
DEALLOCATE(BAC_M)
DEALLOCATE(BAC_E_D)
DEALLOCATE(BAC_S)
DEALLOCATE(BAC_C)
DEALLOCATE(BAC_R)
DEALLOCATE(BAC_RA)
DEALLOCATE(BAC_MSHOV)

DEALLOCATE(BAC_DEAD)
DEALLOCATE(BAC_RATE)


ALLOCATE(BAC_X(BAC_N)) !NEW ARRAY SIZE
ALLOCATE(BAC_Y(BAC_N))
ALLOCATE(BAC_Z(BAC_N))
ALLOCATE(BAC_M(BAC_N))
ALLOCATE(BAC_E_D(BAC_N))
ALLOCATE(BAC_S(BAC_N))
ALLOCATE(BAC_C(BAC_N))
ALLOCATE(BAC_R(BAC_N))
ALLOCATE(BAC_RA(BAC_N))
ALLOCATE(BAC_MSHOV(BAC_N))

ALLOCATE(BAC_DEAD(BAC_N))
ALLOCATE(BAC_RATE(BAC_N,5))

BAC_DEAD=0
BAC_RATE=0.D0

!PRINT*,'TEST9',BAC_E_D
BAC_X(1:BAC_N_OLD)=BAC_X_OLD(1:BAC_N_OLD) !RESTORE OROGINAL DATA
BAC_Y(1:BAC_N_OLD)=BAC_Y_OLD(1:BAC_N_OLD)
BAC_Z(1:BAC_N_OLD)=BAC_Z_OLD(1:BAC_N_OLD)
BAC_M(1:BAC_N_OLD)=BAC_M_OLD(1:BAC_N_OLD)
BAC_E_D(1:BAC_N_OLD)=BAC_E_D_OLD(1:BAC_N_OLD)
BAC_S(1:BAC_N_OLD)=BAC_S_OLD(1:BAC_N_OLD)
BAC_C(1:BAC_N_OLD)=BAC_C_OLD(1:BAC_N_OLD)
BAC_R(1:BAC_N_OLD)=BAC_R_OLD(1:BAC_N_OLD)
BAC_RA(1:BAC_N_OLD)=BAC_RA_OLD(1:BAC_N_OLD)
BAC_MSHOV(1:BAC_N_OLD)=BAC_MSHOV_OLD(1:BAC_N_OLD)

BAC_DEAD(1:BAC_N_OLD)=BAC_DEAD_OLD(1:BAC_N_OLD)
BAC_RATE(1:BAC_N_OLD,:)=BAC_RATE_OLD(1:BAC_N_OLD,:)

!PRINT*,'TEST10',BAC_E_D

BAC_X(BAC_N_OLD+1:BAC_N)=BAC_X_NEW(1:BAC_N_NEW) !STORE NEW DATA INTO THE ARRAYS
BAC_Y(BAC_N_OLD+1:BAC_N)=BAC_Y_NEW(1:BAC_N_NEW)
BAC_Z(BAC_N_OLD+1:BAC_N)=BAC_Z_NEW(1:BAC_N_NEW)
BAC_M(BAC_N_OLD+1:BAC_N)=BAC_M_NEW(1:BAC_N_NEW)
BAC_E_D(BAC_N_OLD+1:BAC_N)=BAC_E_D_NEW(1:BAC_N_NEW)
BAC_S(BAC_N_OLD+1:BAC_N)=BAC_S_NEW(1:BAC_N_NEW)
BAC_C(BAC_N_OLD+1:BAC_N)=BAC_C_NEW(1:BAC_N_NEW)
BAC_R(BAC_N_OLD+1:BAC_N)=BAC_R_NEW(1:BAC_N_NEW)
BAC_RA(BAC_N_OLD+1:BAC_N)=BAC_RA_NEW(1:BAC_N_NEW)
BAC_MSHOV(BAC_N_OLD+1:BAC_N)=BAC_MSHOV_NEW(1:BAC_N_NEW)

!PRINT*,'TEST11=====',BAC_Z

!PAUSE
    IF (BAC_N_OLD+BAC_N_NEW .NE. BAC_N) THEN
        PRINT*,'ERROR IN GROWTH, CHECK NUMBER OF NEW CELLS'
    END IF


END IF
!PAUSE

DEALLOCATE(BAC_X_OLD)
DEALLOCATE(BAC_Y_OLD)
DEALLOCATE(BAC_Z_OLD)
DEALLOCATE(BAC_M_OLD)
DEALLOCATE(BAC_E_D_OLD)
DEALLOCATE(BAC_S_OLD)
DEALLOCATE(BAC_C_OLD)
DEALLOCATE(BAC_R_OLD)
DEALLOCATE(BAC_RA_OLD)
DEALLOCATE(BAC_MSHOV_OLD)

DEALLOCATE(BAC_DEAD_OLD)
DEALLOCATE(BAC_RATE_OLD)

DEALLOCATE(BAC_X_NEW)
DEALLOCATE(BAC_Y_NEW)
DEALLOCATE(BAC_Z_NEW)
DEALLOCATE(BAC_M_NEW)
DEALLOCATE(BAC_E_D_NEW)
DEALLOCATE(BAC_S_NEW)
DEALLOCATE(BAC_C_NEW)
DEALLOCATE(BAC_R_NEW)
DEALLOCATE(BAC_RA_NEW)
DEALLOCATE(BAC_MSHOV_NEW)

!DO I=1,BAC_N
    !IF (BAC_S(I)==5) THEN
     !   PRINT*,'INNERT PARTCILES IN GROWTH',I,BAC_X(I)
    !END IF
!END DO


!PRINT*,'NO OF HET=====',N_HET
!PRINT*,'TEST20',BAC_DEAD
!PAUSE
END SUBROUTINE GROWTH




!============================================================================


!======================SHOVING===============================================
	SUBROUTINE SHOVING()
	USE GLOBAL_VARIABLES
	USE IbM_VARIABLES
	IMPLICIT NONE
	INTEGER::MAX_C
	REAL(8),ALLOCATABLE::MTOT_C(:),MXTOT_C(:),MYTOT_C(:),MZTOT_C(:),VOL_C(:),HOW_MANY(:),BAC_X_C(:),BAC_Y_C(:),BAC_Z_C(:),BAC_M_C(:),BAC_R_C(:),X_C(:),Y_C(:),Z_C(:),X_C0(:),Y_C0(:),Z_C0(:),R_C(:),BAC_XS(:),BAC_YS(:),BAC_ZS(:),BAC_RS(:),DX_C(:),DY_C(:),DZ_C(:)
	INTEGER,ALLOCATABLE::IND_C0(:),SEQ(:),IND_C(:),IND_C1(:),BAC_S_C(:),BAC_C_C(:),POS_HEI(:),IND_HET(:),IND_EPS(:),IND_INERT(:),IND_HET1(:),IND_EPS1(:),IND_INERT1(:),UNITY(:)
	
	
	INTEGER::I,J,K,I_C,SIZE_C,ITE,SIZE_HEI,N1,N4,N5,N145C
	REAL(8)::GAP,THETA,PHI,RADIUS,PI,R_COL,MAX_OVERLAP



	PI=4.D0*DATAN(1.D0)


	MAX_C=MAXVAL(BAC_C) !NUMBER OF COLONIES

	!print*,'SHOVING',MAX_C

	!PAUSE

	ALLOCATE(MTOT_C(MAX_C))     !MASS OF THE COLONY
	ALLOCATE(MXTOT_C(MAX_C))    !MASSxX OF THE COLONY
	ALLOCATE(MYTOT_C(MAX_C))    !MASSxY OF THE COLONY  
	ALLOCATE(MZTOT_C(MAX_C))    !MASSxZ OF THE COLONY
	ALLOCATE(VOL_C(MAX_C))      !VOLUME OF THE COLONY
	ALLOCATE(HOW_MANY(MAX_C))   !NUMBER OF PARTCILES IN THE COLONY
	ALLOCATE(X_C(MAX_C))        !X AT CENTER OF THE COLONY     
	ALLOCATE(Y_C(MAX_C))        !Y AT CENTER OF THE COLONY   
	ALLOCATE(Z_C(MAX_C))        !Z AT CENTER OF THE COLONY   
	ALLOCATE(R_C(MAX_C))        !RADIUS AT CENTER OF THE COLONY   

	ALLOCATE(X_C0(MAX_C))       !STORE OLD DATA
	ALLOCATE(Y_C0(MAX_C))   	!STORE OLD DATA
	ALLOCATE(Z_C0(MAX_C))       !STORE OLD DATA

	ALLOCATE(DX_C(MAX_C))           !DISPLACEMENT OF COLONY IN X DIRECTION
	ALLOCATE(DY_C(MAX_C))       	!DISPLACEMENT OF COLONY IN Y DIRECTION
	ALLOCATE(DZ_C(MAX_C))           !DISPLACEMENT OF COLONY IN Z DIRECTION

	ALLOCATE(IND_C0(BAC_N))     !STORE OLD DATA
	ALLOCATE(IND_C(BAC_N))      !FIND CELLS BELONG TO EACH COLONY
	ALLOCATE(SEQ(BAC_N))        !=1,2,3.....BAC_N
	
	
	SEQ=(/(I,I=1,BAC_N)/)
    !PRINT*,SEQ


	DO I_C=1,MAX_C

		
		WHERE (BAC_C==I_C) 
			
			IND_C0=1

		ELSEWHERE
			IND_C0=0
		END WHERE
			
		IND_C=IND_C0*SEQ

		SIZE_C=SIZE(PACK(IND_C, IND_C /=0)) !NUMBER OF CELLS IN THE COLONY
	
	    IF (SIZE_C>0) THEN  !NUMBER OF CELLS WITHIN EACH COULONY >0
	!	PRINT*,IND_C
	
		ALLOCATE(IND_C1(SIZE_C))

		ALLOCATE(BAC_X_C(SIZE_C)) !CELLS IN THE COLONY
		ALLOCATE(BAC_Y_C(SIZE_C))
		ALLOCATE(BAC_Z_C(SIZE_C))
		ALLOCATE(BAC_M_C(SIZE_C))
		ALLOCATE(BAC_R_C(SIZE_C))
		ALLOCATE(BAC_S_C(SIZE_C))
		ALLOCATE(BAC_C_C(SIZE_C))

		
		IND_C1=PACK(IND_C, IND_C /=0) !INDICES OF CELLS IN THE COLONY

	!	PRINT*,IND_C1
	    
	
		BAC_X_C=BAC_X(IND_C1)
		BAC_Y_C=BAC_Y(IND_C1)
		BAC_Z_C=BAC_Z(IND_C1)
		BAC_M_C=BAC_M(IND_C1)
		BAC_R_C=BAC_R(IND_C1)
		BAC_S_C=BAC_S(IND_C1)
		BAC_C_C=BAC_C(IND_C1)


		MTOT_C(I_C)=SUM(BAC_M_C)            !MASS OF THE COLONY
		MXTOT_C(I_C)=SUM(BAC_M_C*BAC_X_C)   !MASSxX OF THE COLONY
		MYTOT_C(I_C)=SUM(BAC_M_C*BAC_Y_C)   !MASSxY OF THE COLONY
		MZTOT_C(I_C)=SUM(BAC_M_C*BAC_Z_C)   !MASSxZ OF THE COLONY
		VOL_C(I_C)=4.D0*PI*(SUM(BAC_R_C**3))/3.D0 !VOLUME OF THE COLONY
		HOW_MANY(I_C)=SIZE_C                    !NUMBER OF CELLS WITHIN THE COLONY


		
		X_C(I_C)=MXTOT_C(I_C)/MTOT_C(I_C)
		Y_C(I_C)=MYTOT_C(I_C)/MTOT_C(I_C)
		Z_C(I_C)=MZTOT_C(I_C)/MTOT_C(I_C)


	!	PRINT*,RCOL
	!	PAUSE

        R_COL=1
		IF (HOW_MANY(I_C)==2) THEN
			R_COL=RCOL(1)     !R_COL IS A FACTOR TO INCOPORATE THE GAPS BETWEEN PARTCILES INTO THE COLONY VOLUME
		ELSE IF (HOW_MANY(I_C)>2) THEN
			R_COL=RCOL(2)
		END IF

		R_C(I_C)=(3.D0*VOL_C(I_C)*R_COL/(4.D0*PI))**(1.D0/3.D0) !RADIUS OF THE COLONY

		
		
		!============SHOVING WITHIN COLONIES===============
		IF (SIZE_C>1) THEN
		    DO ITE=1,30
	
			    CALL SHOVING_ALGORITHM(SIZE_C,BAC_X_C,BAC_Y_C,BAC_Z_C,BAC_R_C,SHOVING_FACTOR,MAX_OVERLAP)

            END DO
            
            BAC_X(IND_C1)=BAC_X_C   !UPDAE FOR NEW POSITION
		    BAC_Y(IND_C1)=BAC_Y_C   !UPDAE FOR NEW POSITION
		    BAC_Z(IND_C1)=BAC_Z_C   !UPDAE FOR NEW POSITION
            IF (MAX_OVERLAP<0.01D0) GOTO 50
        !    PAUSE
        END IF
50      CONTINUE		
		!==================================================
		
		
		
		
		
		
		!PRINT*,MXTOT_C(I_C)



		DEALLOCATE(IND_C1)
		DEALLOCATE(BAC_X_C)
		DEALLOCATE(BAC_Y_C)
		DEALLOCATE(BAC_Z_C)
		DEALLOCATE(BAC_M_C)
		DEALLOCATE(BAC_R_C)
		DEALLOCATE(BAC_S_C)
		DEALLOCATE(BAC_C_C)

        END IF

	END DO


!	RE-CALCULATE THE CENTER OF MASS FOR EACH COLONY


    DO I_C=1,MAX_C

		
		WHERE (BAC_C==I_C) 
			
			IND_C0=1

		ELSEWHERE
			IND_C0=0
		END WHERE
			
		IND_C=IND_C0*SEQ

		SIZE_C=SIZE(PACK(IND_C, IND_C /=0))
	
	
		!PRINT*,SIZE_C
	
		ALLOCATE(IND_C1(SIZE_C))

		ALLOCATE(BAC_X_C(SIZE_C))
		ALLOCATE(BAC_Y_C(SIZE_C))
		ALLOCATE(BAC_Z_C(SIZE_C))
		ALLOCATE(BAC_M_C(SIZE_C))
		ALLOCATE(BAC_R_C(SIZE_C))
		ALLOCATE(BAC_S_C(SIZE_C))
		ALLOCATE(BAC_C_C(SIZE_C))

		
		IND_C1=PACK(IND_C, IND_C /=0)

		
	
	
		BAC_X_C=BAC_X(IND_C1)
		BAC_Y_C=BAC_Y(IND_C1)
		BAC_Z_C=BAC_Z(IND_C1)
		BAC_M_C=BAC_M(IND_C1)
		BAC_R_C=BAC_R(IND_C1)
		BAC_S_C=BAC_S(IND_C1)
		BAC_C_C=BAC_C(IND_C1)


		MTOT_C(I_C)=SUM(BAC_M_C)
		MXTOT_C(I_C)=SUM(BAC_M_C*BAC_X_C)
		MYTOT_C(I_C)=SUM(BAC_M_C*BAC_Y_C)
		MZTOT_C(I_C)=SUM(BAC_M_C*BAC_Z_C)
		VOL_C(I_C)=4.D0*PI*SUM(BAC_R_C**3)/3.D0
		HOW_MANY(I_C)=SIZE_C


		
		X_C(I_C)=MXTOT_C(I_C)/MTOT_C(I_C)
		Y_C(I_C)=MYTOT_C(I_C)/MTOT_C(I_C)
		Z_C(I_C)=MZTOT_C(I_C)/MTOT_C(I_C)

        R_COL=1
		IF (HOW_MANY(I_C)==2 ) THEN
			R_COL=RCOL(1)
		ELSE IF (HOW_MANY(I_C)>2) THEN
			R_COL=RCOL(2)
		END IF

		R_C(I_C)=(3.D0*VOL_C(I_C)*R_COL/(4.D0*PI))**(1.D0/3.D0)

		
		
				
		!PRINT*,MXTOT_C(I_C)



		DEALLOCATE(IND_C1)
		DEALLOCATE(BAC_X_C)
		DEALLOCATE(BAC_Y_C)
		DEALLOCATE(BAC_Z_C)
		DEALLOCATE(BAC_M_C)
		DEALLOCATE(BAC_R_C)
		DEALLOCATE(BAC_S_C)
		DEALLOCATE(BAC_C_C)



	END DO  !END FOR SHOVING WITHIN COLONIES
	
!INDEX FOR HET, EPS, INERT===============

	ALLOCATE(POS_HEI(BAC_N))  !POSITION OF HET/EPS/INERT
	ALLOCATE(IND_HET(BAC_N))
	ALLOCATE(IND_EPS(BAC_N))
	ALLOCATE(IND_INERT(BAC_N))
!========HET=====================
	WHERE (BAC_S==1)
		POS_HEI=1
	ELSEWHERE
		POS_HEI=0
	END WHERE

	IND_HET=POS_HEI*SEQ
	
	SIZE_HEI=SIZE(PACK(IND_HET, IND_HET /=0))
	N1=SIZE_HEI  !NUMBER OF HET

	ALLOCATE(IND_HET1(SIZE_HEI))

	IND_HET1=PACK(IND_HET, IND_HET /=0)

!=======EPS=======================
	WHERE (BAC_S==4)
		POS_HEI=1
    ELSEWHERE
       POS_HEI=0
    END WHERE

	IND_EPS=POS_HEI*SEQ
	
	SIZE_HEI=SIZE(PACK(IND_EPS, IND_EPS /=0))
	N4=SIZE_HEI !NUMBER OF EPS

	ALLOCATE(IND_EPS1(SIZE_HEI))

	IND_EPS1=PACK(IND_EPS, IND_EPS /=0)

!=======INERT======================
	WHERE (BAC_S==5)
		POS_HEI=1
	ELSEWHERE
		POS_HEI=0
	END WHERE

	IND_INERT=POS_HEI*SEQ
	
	SIZE_HEI=SIZE(PACK(IND_INERT, IND_INERT /=0))
	N5=SIZE_HEI !NUMBER OF INERT

	ALLOCATE(IND_INERT1(SIZE_HEI))

	IND_INERT1=PACK(IND_INERT, IND_INERT /=0)

!==================================	
!PRINT*,MAX_C
!PAUSE
	N145C=N1+N4+N5+MAX_C   ! NUMBER OF (HET + EPS + INERT + COLONIES)

	ALLOCATE(BAC_XS(N145C))
	ALLOCATE(BAC_YS(N145C))
	ALLOCATE(BAC_ZS(N145C))
	ALLOCATE(BAC_RS(N145C))


	BAC_XS=(/BAC_X(IND_HET1), BAC_X(IND_EPS1), BAC_X(IND_INERT1), X_C/)
	
	BAC_YS=(/BAC_Y(IND_HET1), BAC_Y(IND_EPS1), BAC_Y(IND_INERT1), Y_C/)

	BAC_ZS=(/BAC_Z(IND_HET1), BAC_Z(IND_EPS1), BAC_Z(IND_INERT1), Z_C/)

	BAC_RS=(/BAC_R(IND_HET1), BAC_R(IND_EPS1), BAC_R(IND_INERT1), R_C/)

!PRINT*,'TEST100'

!PRINT*,BAC_XS
!PAUSE

	!============SHOVING HET_EPS_INERT+COLONIES===============
		
	!	IF (MOD(ITER_GROWTH,10)==0) THEN
		
		DO ITE=1,30
	
			CALL SHOVING_ALGORITHM(N145C,BAC_XS,BAC_YS,BAC_ZS,BAC_RS,SHOVING_FACTOR,MAX_OVERLAP)
        !    PRINT*,MAX_OVERLAP
            IF (MAX_OVERLAP<0.01D0) GOTO 100
        END DO
        
100     CONTINUE        
	!	END IF
		
	!=================UPDATE THE POSITIONS====================

	BAC_X(IND_HET1)=BAC_XS(1:N1)
	BAC_Y(IND_HET1)=BAC_YS(1:N1)
	BAC_Z(IND_HET1)=BAC_ZS(1:N1)

	
	BAC_X(IND_EPS1)=BAC_XS(N1+1:N1+N4)
	BAC_Y(IND_EPS1)=BAC_YS(N1+1:N1+N4)
	BAC_Z(IND_EPS1)=BAC_ZS(N1+1:N1+N4)

	BAC_X(IND_INERT1)=BAC_XS(N1+N4+1:N1+N4+N5)
	BAC_Y(IND_INERT1)=BAC_YS(N1+N4+1:N1+N4+N5)
	BAC_Z(IND_INERT1)=BAC_ZS(N1+N4+1:N1+N4+N5)



	X_C0=X_C
	Y_C0=Y_C
	Z_C0=Z_C

	X_C(1:MAX_C)=BAC_XS(N1+N4+N5+1:N145C)
	Y_C(1:MAX_C)=BAC_YS(N1+N4+N5+1:N145C)
	Z_C(1:MAX_C)=BAC_ZS(N1+N4+N5+1:N145C)


	DX_C=X_C-X_C0   !DISPLACEMENTS OF COLONIES
	DY_C=Y_C-Y_C0
	DZ_C=Z_C-Z_C0


!DO I=1,BAC_N
  !  IF (BAC_S(I)==5) THEN
    !    PRINT*,'INNERT PARTICLES IN SHOVING1',I,BAC_X(I)
   ! END IF
!END DO

        




!	PRINT*,'COLONY MOVEMENT',Z_C

!PAUSE

	!========UPDATE AOB, NOB IN EACH COLONY=============


	

	!PAUSE

	DO I_C=1,MAX_C

		
		WHERE (BAC_C==I_C) 
			
			IND_C0=1

		ELSEWHERE
			IND_C0=0
		END WHERE
			
		IND_C=IND_C0*SEQ

		SIZE_C=SIZE(PACK(IND_C, IND_C /=0))
	
	
		!PRINT*,SIZE_C
	
		ALLOCATE(IND_C1(SIZE_C))

	!		PAUSE	
		IND_C1=PACK(IND_C, IND_C /=0)

		ALLOCATE(UNITY(SIZE_C))

		UNITY=1
	
		BAC_X(IND_C1)=BAC_X(IND_C1) +DX_C(I_C)*UNITY
		BAC_Y(IND_C1)=BAC_Y(IND_C1) +DY_C(I_C)*UNITY
		BAC_Z(IND_C1)=BAC_Z(IND_C1) +DZ_C(I_C)*UNITY

	
		
		DEALLOCATE(IND_C1)
		DEALLOCATE(UNITY)	
	
	END DO



!PRINT*,N145,BAC_N

!PAUSE


!FLOC SIZE/POSITION CALCULATOR

FLOC_VOL=4.D0*PI*SUM(BAC_R**3)/3.D0
FLOC_VOL=FLOC_VOL*RCOL(2)
FLOC_RADIUS=(3.D0*FLOC_VOL/(4.D0*PI))**(1.D0/3.D0)  !RADIUS OF THE FLOC
FLOC_CENTER(1)=SUM(BAC_X)/(BAC_N)   !X COORDINATE OF CENTER OF FLOC
FLOC_CENTER(2)=SUM(BAC_Y)/(BAC_N)   !Y COORDINATE OF CENTER OF FLOC
FLOC_CENTER(3)=SUM(BAC_Z)/(BAC_N)   !Z COORDINATE OF CENTER OF FLOC

PRINT*,'======@@@============='
PRINT*,'FLOC RADIUS=',FLOC_RADIUS
PRINT*,'FLOC POSITION=',FLOC_CENTER(1),FLOC_CENTER(2),FLOC_CENTER(3)
PRINT*,'======@@@============='
!PRINT*,IND_C
!PAUSE

	

!PRINT*,BAC_X(1),'=================='

!DO I=1,BAC_N
  !  IF (BAC_S(I)==5) THEN
   !     PRINT*,'INNERT PARTICLES IN SHOVING2',I,BAC_X(I)
  !  END IF
!END DO

	

	END SUBROUTINE SHOVING
!===========================================================================	

	SUBROUTINE SHOVING_ALGORITHM(N,X,Y,Z,R,FACTOR,MAX_OVERLAP)
	IMPLICIT NONE
	INTEGER::N,I,J,II,LOOP_START,LOOP_END
	REAL(8)::X(N),Y(N),Z(N),R(N),FACTOR,SHOVING_VECTOR(N,3),GAP,THETA,PHI,RADIUS,MAX_OVERLAP,OVERLAP
    REAL(4)::RAN
    
    MAX_OVERLAP=0.D0
    !REFERENCE FOR THE SHOVING ALGORITH: PICIOREANU ET AL. (2004)
    CALL RANDOM_SEED()
    
    CALL RANDOM_NUMBER(RAN)

    II=FLOOR(RAN*N) !VERSION2 IMPROVEMENTS: START SHOVING AT A RANDOMLY SELECTED PARTICLE
    IF (II<1) II=1
    LOOP_START=II
    LOOP_END=N
	DO I=LOOP_START,LOOP_END

		SHOVING_VECTOR(I,:)=0.D0

		DO J=1,N

			IF (I .NE. J) THEN

				GAP=(X(J)-X(I))**2+(Y(J)-Y(I))**2+(Z(J)-Z(I))**2
				GAP=DSQRT(GAP)

		!		THETA=DACOS((Z(J)-Z(I))/GAP)
		!		PHI=DATAN((Y(J)-Y(I))/(X(J)-X(I)))
				
				RADIUS=FACTOR*(R(I)+R(J))-GAP

				IF (RADIUS>0.D0) THEN
                    OVERLAP=RADIUS/(R(I)+R(J))
                    IF (MAX_OVERLAP<OVERLAP) MAX_OVERLAP=OVERLAP

		!		PRINT*,'SHOVING',I,J,RADIUS,BAC_R(I)
				
		!		PAUSE

			!	SHOVING_VECTOR(I,1)=SHOVING_VECTOR(I,1)+RADIUS*DSIN(THETA)*DCOS(PHI)
			!	SHOVING_VECTOR(I,2)=SHOVING_VECTOR(I,2)+RADIUS*DSIN(THETA)*DSIN(PHI)
			!	SHOVING_VECTOR(I,3)=SHOVING_VECTOR(I,3)+RADIUS*DCOS(THETA)
                    
				!VERSION2 IMPROVEMENTS
                SHOVING_VECTOR(I,1)=SHOVING_VECTOR(I,1)+((X(J)-X(I))/GAP)*RADIUS
				SHOVING_VECTOR(I,2)=SHOVING_VECTOR(I,2)+((Y(J)-Y(I))/GAP)*RADIUS
				SHOVING_VECTOR(I,3)=SHOVING_VECTOR(I,3)+((Z(J)-Z(I))/GAP)*RADIUS
                
                
				END IF

			END IF


		END DO

	!	PRINT*,	BAC_X(I),BAC_R(I),SHOVING_VECTOR(I,1),'==============='
	!	PAUSE
		
		X(I)=X(I)-SHOVING_VECTOR(I,1)
		Y(I)=Y(I)-SHOVING_VECTOR(I,2)
		Z(I)=Z(I)-SHOVING_VECTOR(I,3)


      IF (I==LOOP_END) THEN
          LOOP_START=1
          LOOP_END=II-1
      ELSE IF (I==II-1) THEN
          GOTO 100
      END IF
      
          
	END DO

100 CONTINUE		

	END SUBROUTINE SHOVING_ALGORITHM

!============================================================================

!====================IbM SOLVER==============================================

SUBROUTINE IbM_SOLVER()
USE GLOBAL_VARIABLES
USE IbM_VARIABLES
USE REACTOR_VARIABLES


IMPLICIT NONE

INTEGER::ITE

!==============ATTACHMENT=======================

MFLOC_OLD=SUM(BAC_M+BAC_E_D)

IF (MOD(ITER_GROWTH,N_SINGLE_ATTACH)==0) THEN
!PAUSE
CALL SINGLE_CELL_ATTACHMENT()

END IF


MFLOC_NEW=SUM(BAC_M+BAC_E_D)

IF (BIOREACTOR==1) THEN
    NFLOCS=NFLOCS*MFLOC_OLD/MFLOC_NEW
END IF

!PRINT*,'ATTACHMENT-PASSED'

!==============GROWING & DIVISION==========================

!PRINT*,BAC_C,BAC_N

!PAUSE
CALL GROWTH()

!PRINT*,'GROWTH-PASSED'
!==============SHOVING==========================
!PAUSE
IF (MOD(ITER_GROWTH,N_SHOVING_INTERVAL)==0) THEN
CALL SHOVING()
END IF

!PRINT*,'SHOVING-PASSED'
!===============================================

END SUBROUTINE IbM_SOLVER
!==========================OUTPUT===========================================

SUBROUTINE OUT(IFRAME)
USE GLOBAL_VARIABLES,ONLY:MX,MY,MZ,S_S,S_O2,S_NO2,S_NO3,S_NH4
!USE IbM_VARIABLES
IMPLICIT NONE
INTEGER::IFRAME,I,J,K
CHARACTER (4)  :: STR
CHARACTER (30)  :: FILENAME

	FILENAME = "CONCENTRATION_"
	IF(IFRAME>=1000) THEN
		WRITE (STR,'(I4)') IFRAME
		FILENAME = trim(FILENAME)//trim(STR)//".dat"
	ELSEIF(IFRAME>=100) THEN
		WRITE (STR,'(I3)') IFRAME
		FILENAME = trim(FILENAME)//"0"//trim(STR)//".dat"
	ELSEIF(IFRAME>=10) THEN
		WRITE (STR,'(I2)') IFRAME
		FILENAME = trim(FILENAME)//"00"//trim(STR)//".dat"
	ELSE
		WRITE (STR,'(I1)') IFRAME
		FILENAME = trim(FILENAME)//"000"//trim(STR)//".dat"
    ENDIF
	
    OPEN(50,file=FILENAME,form='formatted',status='unknown')

    DO I=1,MX
        DO J=1,MY
            DO K=1,MZ
                WRITE(50,19),I,J,K,S_O2(I,J,K)
            END DO
        END DO
    END DO
 19	FORMAT(3I3,E12.4)   

    END SUBROUTINE OUT

!==========================CONTINUOUS MODEL=================================
SUBROUTINE CONTINUOUS_MODEL(ITE,C_MASS_HET,C_MASS_AOB,C_MASS_NOB,C_MASS_HET_EPS,C_MASS_PAR_EPS,C_MASS_INERT)
USE GLOBAL_VARIABLES,ONLY:LX,LY,LZ,DT_BIO,TIME_BIO,TOTAL_TIME_BIO,MU_M_HET,MU_M_AOB,MU_M_NOB,B_HET,B_EPS,B_AOB,B_NOB,K_O2_HET,K_S_HET,K_NO2_HET,K_NO3_HET,K_O2_AOB,K_NH4_AOB,K_O2_NOB,K_NO2_NOB,Y_HET,Y_EPS,Y_AOB,Y_NOB,Y_I,ETA_H
USE IbM_VARIABLES,ONLY:MASS_HET,MASS_AOB,MASS_NOB,MASS_EPS,MASS_INERT,BAC_RHO,BAC_RHOD,BAC_RHOE,BIOREACTOR,N_SINGLE_ATTACH
USE	REACTOR_VARIABLES,ONLY:V_R,ALPHA,BETA,HRT,SRT,Q_O2,M_BIOMASS,S_O2_R,S_S_R,S_NO2_R,S_NO3_R,S_NH4_R

IMPLICIT NONE
INTEGER::ITE,I,J,K
REAL(8)::C_MASS_HET,C_MASS_AOB,C_MASS_NOB,C_MASS_HET_EPS,C_MASS_PAR_EPS,C_MASS_INERT,NEW_DECAY_MASS,RATE,C_S,C_O2,C_NH4,C_NO2,C_NO3,NEW_CARBON,NEW_HET,NEW_HET_EPS,RAN

NEW_DECAY_MASS=0.D0
NEW_CARBON=0.D0

C_S=S_S_R
C_O2=S_O2_R
C_NO2=S_NO2_R
C_NO3=S_NO3_R
C_NH4=S_NH4_R

CALL RANDOM_SEED()
CALL RANDOM_NUMBER(RAN)

!   HET MASS
RATE=MU_M_HET*(C_S/(K_S_HET+C_S))*(C_O2/(K_O2_HET+C_O2))  !AEROBIC GROWTH
RATE=RATE+ETA_H*MU_M_HET*(C_S/(K_S_HET+C_S))*(C_NO3/(K_NO3_HET+C_NO3))*(K_O2_HET/(K_O2_HET+C_O2))   !ANOXIC GROWTH ON NO3
RATE=RATE+ETA_H*MU_M_HET*(C_S/(K_S_HET+C_S))*(C_NO2/(K_NO2_HET+C_NO2))*(K_O2_HET/(K_O2_HET+C_O2))   !ANOXIC GROWTH ON NO2   
RATE=RATE  !TOTAL GROWTH RATE

NEW_DECAY_MASS=NEW_DECAY_MASS+DT_BIO*B_HET*C_MASS_HET*Y_I  !DECAY MASS FROM HET
NEW_CARBON=NEW_CARBON+DT_BIO*B_HET*C_MASS_HET*(1.D0-Y_I)    !CARBON FROM HET

NEW_HET=DT_BIO*(RATE-B_HET)*C_MASS_HET
C_MASS_HET=C_MASS_HET+NEW_HET    !TOTAL HET MASS






!   EPS MASS
NEW_CARBON=NEW_CARBON+DT_BIO*B_EPS*C_MASS_PAR_EPS*(1.D0) 
C_MASS_PAR_EPS=C_MASS_PAR_EPS-DT_BIO*B_EPS*C_MASS_PAR_EPS*(1.D0) 

NEW_HET_EPS=DT_BIO*RATE*C_MASS_HET*Y_EPS/Y_HET
C_MASS_HET_EPS=C_MASS_HET_EPS+NEW_HET_EPS

IF (C_MASS_HET_EPS>0.953D0*C_MASS_HET*BAC_RHOE/BAC_RHO) THEN
    C_MASS_HET_EPS=C_MASS_HET_EPS/2.D0
    C_MASS_PAR_EPS=C_MASS_PAR_EPS+C_MASS_HET_EPS
END IF

!   AOB MASS

RATE=MU_M_AOB*(C_NH4/(K_NH4_AOB+C_NH4))*(C_O2/(K_O2_AOB+C_O2))
RATE=(RATE-B_AOB)*C_MASS_AOB
!PRINT*,'RRR',RATE
NEW_DECAY_MASS=NEW_DECAY_MASS+DT_BIO*B_AOB*C_MASS_AOB*Y_I
NEW_CARBON=NEW_CARBON+DT_BIO*B_AOB*C_MASS_AOB*(1.D0-Y_I)
C_MASS_AOB=C_MASS_AOB+DT_BIO*RATE


!   NOB MASS

RATE=MU_M_NOB*(C_NO2/(K_NO2_NOB+C_NO2))*(C_O2/(K_O2_NOB+C_O2))
RATE=(RATE-B_NOB)*C_MASS_NOB

NEW_CARBON=NEW_CARBON+DT_BIO*B_NOB*C_MASS_NOB*(1.D0-Y_I)
NEW_DECAY_MASS=NEW_DECAY_MASS+DT_BIO*B_NOB*C_MASS_NOB*Y_I


C_MASS_NOB=C_MASS_NOB+DT_BIO*RATE

!PRINT*,'NOB_GR=====',MASS_NOB
!PRINT*,'RATE=',RATE
!   INERT MASS

C_MASS_INERT=C_MASS_INERT+NEW_DECAY_MASS

!   NEW CARBON CONCENTRATION
C_S=C_S  !+NEW_CARBON/(LX*LY*LZ)

!SINGLE CELL ATTACHMENT
IF (MOD(ITE,N_SINGLE_ATTACH)==0) THEN
    
    IF (RAN<=0.6D0) THEN
        C_MASS_HET=C_MASS_HET+MASS_HET
        
    
    END IF
    
    IF (RAN>0.6D0 .AND. RAN<=0.8D0) THEN
        C_MASS_AOB=C_MASS_AOB+MASS_AOB
    END IF
    
    IF (RAN>0.8D0) THEN
        C_MASS_NOB=C_MASS_NOB+MASS_NOB
    END IF
    
END IF

!PAUSE

END SUBROUTINE CONTINUOUS_MODEL

!############################################################################

!****************************************************************************
!
!  PROGRAM: GLOBAL
!
!  PURPOSE:  IbM BIOLOGICAL SOLVER.
!
!****************************************************************************

PROGRAM MAIN
    USE GLOBAL_VARIABLES
    USE BCND
	USE IbM_VARIABLES
	USE REACTOR_VARIABLES

    IMPLICIT NONE
    INTEGER::I,J,K,IFRAME,COUNT1,COUNT2,COUNT3,COUNT4,COUNT5
	REAL(8)::S_RESIDUAL,F_HET,F_AOB,F_NOB,F_EPS,F_INERT,TIME_BEGIN,TIME_END
    REAL(8)::C_MASS_HET,C_MASS_AOB,C_MASS_NOB,C_MASS_HET_EPS,C_MASS_PAR_EPS,C_MASS_INERT !MASS CALCULATED BY CONTINUOUS MODEL
    REAL(8)::I_MASS_HET,I_MASS_AOB,I_MASS_NOB,I_MASS_HET_EPS,I_MASS_PAR_EPS,I_MASS_INERT !MASS CALCULATED BY IbM MODEL
    REAL(8)::STORE_DATA1(5000),STORE_DATA2(5000),STORE_DATA3(5000),STORE_DATA4(5000),STORE_DATA5(5000),STORE_DATA6(5000),STORE_DATA7(5000),STORE_DATA8(5000),STORE_DATA9(5000),STORE_DATA10(5000),STORE_DATA11(5000),STORE_DATA12(5000)
    
    
    
  !  print *, 'Hello World'
    ALLOCATE(RCOL(2))
    
	CALL DOMAIN
    CALL PARAMETERS
    
    ALLOCATE(XS(MX))
    ALLOCATE(YS(MY))
    ALLOCATE(ZS(MZ))
    ALLOCATE(UX(MX+1,MY,MZ))
    ALLOCATE(UY(MX,MY+1,MZ))
    ALLOCATE(UZ(MX,MY,MZ+1))
    ALLOCATE(S_O2(MX,MY,MZ))
    ALLOCATE(S_NO2(MX,MY,MZ))
    ALLOCATE(S_NO3(MX,MY,MZ))
    ALLOCATE(S_NH4(MX,MY,MZ))
    ALLOCATE(S_S(MX,MY,MZ))
   
    ALLOCATE(D_O2(MX,MY,MZ))
    ALLOCATE(D_NO2(MX,MY,MZ))
    ALLOCATE(D_NO3(MX,MY,MZ))
    ALLOCATE(D_NH4(MX,MY,MZ))
    ALLOCATE(D_S(MX,MY,MZ))

	ALLOCATE(X_HET(MX,MY,MZ))
    ALLOCATE(X_AOB(MX,MY,MZ))
    ALLOCATE(X_NOB(MX,MY,MZ))
    ALLOCATE(X_EPS(MX,MY,MZ))
    ALLOCATE(X_I(MX,MY,MZ))
	ALLOCATE(X_S(MX,MY,MZ))
    
    ALLOCATE(XBPS(MY,MZ))
    ALLOCATE(XBNS(MY,MZ))
    ALLOCATE(YBPS(MX,MZ))
    ALLOCATE(YBNS(MX,MZ))
    ALLOCATE(ZBPS(MX,MY))
    ALLOCATE(ZBNS(MX,MY))
    
    ALLOCATE(R_O2(MX,MY,MZ))
	ALLOCATE(R_S(MX,MY,MZ))
	ALLOCATE(R_NH4(MX,MY,MZ))
	ALLOCATE(R_NO2(MX,MY,MZ))
	ALLOCATE(R_NO3(MX,MY,MZ))

	
	ALLOCATE(BAC_M(BAC_N))
	ALLOCATE(BAC_MSHOV(BAC_N))
	ALLOCATE(BAC_E_D(BAC_N))
	ALLOCATE(BAC_S(BAC_N))
	ALLOCATE(BAC_C(BAC_N))
	ALLOCATE(BAC_R(BAC_N))
	ALLOCATE(BAC_RA(BAC_N))
	ALLOCATE(BAC_X(BAC_N))
	ALLOCATE(BAC_Y(BAC_N))
	ALLOCATE(BAC_Z(BAC_N))

	ALLOCATE(BAC_MMAX(3))
	

	ALLOCATE(BIOMASS_OCCUPANCY(MX,MY,MZ))
    ALLOCATE(FLOC_CENTER(3))
    
    ALLOCATE(BAC_RATE(BAC_N,5))
    ALLOCATE(BAC_DEAD(BAC_N))

    
    !INITIAL VALUES FOR CONTINOUS MODEL
    C_MASS_HET=MASS_HET
    C_MASS_HET_EPS=MASS_EPS
    C_MASS_PAR_EPS=MASS_EPS
    C_MASS_AOB=MASS_AOB
    C_MASS_NOB=MASS_NOB
    C_MASS_INERT=MASS_INERT
    
   !PAUSE
   
   
   CALL IC()
   
   CALL DIF_COEF()
   !PAUSE
   
	OPEN (UNIT=1, FILE='RESULTS.TXT')
	OPEN (UNIT=2, FILE='NUTRIENTS.vtk')
	OPEN (UNIT=3, FILE='res1.vtk')
	OPEN(UNIT=4,FILE='PARTICLES.DAT')
	OPEN(UNIT=5,FILE='RADIUS.XML')
	OPEN(UNIT=10,FILE='MASS_FRACTIONS.TXT')
	OPEN(UNIT=11,FILE='FLOCS_DIAMETER.TXT')
	OPEN(UNIT=12,FILE='NO_OF_FLOCS.TXT')
	OPEN(UNIT=13,FILE='NO_OF_COLONIES.TXT')
	OPEN(UNIT=14,FILE='COMPUTATIONA_TIME.TXT')
    OPEN(UNIT=15,FILE='CONTINUOUS_IbM_COMPARISON.TXT')
    OPEN(UNIT=100,FILE='F_HET.TXT')
    OPEN(UNIT=101,FILE='F_AOB.TXT')
    OPEN(UNIT=102,FILE='F_NOB.TXT')
    OPEN(UNIT=103,FILE='F_EPS.TXT')
    OPEN(UNIT=104,FILE='F_INERT.TXT')
    OPEN(UNIT=105,FILE='TOTAL_PARTICLES.TXT')
    
    OPEN(UNIT=201,FILE='MASS_AOB_IbM.TXT')
    OPEN(UNIT=202,FILE='MASS_AOB_C.TXT')
    OPEN(UNIT=203,FILE='MASS_HET_IbM.TXT')
    OPEN(UNIT=204,FILE='MASS_HET_C.TXT')
    OPEN(UNIT=205,FILE='MASS_NOB_IbM.TXT')
    OPEN(UNIT=206,FILE='MASS_NOB_C.TXT')
    OPEN(UNIT=207,FILE='MASS_EPS_IbM.TXT')
    OPEN(UNIT=208,FILE='MASS_INERT_IbM.TXT')
    
    
    OPEN(UNIT=301,FILE='MASS_S.TXT')
    OPEN(UNIT=302,FILE='MASS_O2.TXT')
    OPEN(UNIT=303,FILE='MASS_NO2.TXT')
    OPEN(UNIT=304,FILE='MASS_NO3.TXT')
    OPEN(UNIT=305,FILE='MASS_NH4.TXT')
    
    
    
    OPEN(UNIT=401,FILE='HET_S_CONSUMPTION.TXT')
    OPEN(UNIT=402,FILE='HET_O2_CONSUMPTION.TXT')
    OPEN(UNIT=403,FILE='HET_NO2_CONSUMPTION.TXT')
    OPEN(UNIT=404,FILE='HET_NO3_CONSUMPTION.TXT')
    
    OPEN(UNIT=405,FILE='AOB_O2_CONSUMPTION.TXT')
    OPEN(UNIT=406,FILE='AOB_NH4_CONSUMPTION.TXT')
    OPEN(UNIT=407,FILE='AOB_NO2_EXCRETION.TXT')
    
    OPEN(UNIT=408,FILE='NOB_O2_CONSUMPTION.TXT')
    OPEN(UNIT=409,FILE='NOB_NO2_CONSUMPTION.TXT')
    OPEN(UNIT=410,FILE='NOB_NO3_EXCRETION.TXT')
    
    OPEN(UNIT=411,FILE='EPS_S_EXCRETION.TXT')
    OPEN(UNIT=412,FILE='DEAD_S_EXCRETION.TXT')
    
  CALL BIOMASS_ON_GRID()
  
   TIME_BIO=0.D0
   IFRAME=0
   
    STORE_DATA1=0.D0
    STORE_DATA2=0.D0
    STORE_DATA3=0.D0
    STORE_DATA4=0.D0
    STORE_DATA5=0.D0
    STORE_DATA6=0.D0
    STORE_DATA7=0.D0
    STORE_DATA8=0.D0
    STORE_DATA9=0.D0
    STORE_DATA10=0.D0
    STORE_DATA11=0.D0
    STORE_DATA12=0.D0
    !========================START ITERATION=======================
    !==============================================================
    !==============================================================
    
    DO ITER_GROWTH=1,N_GROWTH

    IFRAME=IFRAME+1
   CALL CPU_TIME(TIME_BEGIN)

 !  DO WHILE (TIME_BIO<TOTAL_TIME_BIO)   !RUN FOR THE TOTAL BIOLOGICAL TIME
	!	PRINT*,'TEST25'
		
 !  DO I=1,BAC_N
!       IF (BAC_S(I)==5) THEN
      !     PRINT*,'INERT PARTCILES BEFORE BIOMASS',I,BAC_X(I)
     !  END IF
   !END DO
   
   
 !  CALL BIOMASS_ON_GRID()
!		PRINT*,'TEST50'
		TIME_PHY=0.D0
   
	
		IF (MASS_TRANSFER==1) THEN
		
		DO WHILE (TIME_PHY<TOTAL_TIME_PHY) !RUN FOR THE TOTAL PHYSICAL TIME
			
			
			CALL MASS_TRANSPORT_SOLVER(S_RESIDUAL)	!SUBSTRATE CONVECTION-DIFFUSION-REACTION
   
			!PAUSE
			! PRINT*,LX
			TIME_PHY=TIME_PHY+DT_PHY
			PRINT*,'PHYSICAL TIME=',TIME_PHY,S_RESIDUAL
		!	PRINT*,S_O2(MX/2,MY/2,2),S_O2(MX/2,MY/2,MZ-1)
            IF (S_RESIDUAL<1.D-6) TIME_PHY=TOTAL_TIME_PHY
		END DO
        END IF
        
        IF (MINVAL(S_S)<0.D0 .OR. MINVAL(S_O2)<0.D0 .OR.MINVAL(S_NH4)<0.D0 .OR.MINVAL(S_NO2)<0.D0 .OR.MINVAL(S_NO3)<0.D0) THEN
            PRINT*,'NEGATIVE VALUES FOR STEADY CONCENTRATION'
            PAUSE
        END IF
        

!	PRINT*,S_NO2(1,1,1)

	!	PAUSE

		
		TIME_BIO=TIME_BIO+DT_BIO
		
   	!	PAUSE

		!CONSTANT CONCENTRATION FIELDS
      !  S_S=S_S_R
      !  S_O2=S_O2_R
      ! S_NO2=S_NO2_R
      !  S_NO3=S_NO3_R
      !  S_NH4=S_NH4_R

	!	PAUSE
	!	PRINT*,'TEST100'
		CALL IbM_SOLVER()
	!	PRINT*,'TEST200'
		
	!	DO I=1,BAC_N
      ! IF (BAC_S(I)==5) THEN
      !     PRINT*,'INERT PARTCILES AFTER IbM',I,BAC_X(I)
     !  END IF
   ! END DO
        PRINT*,'=========================='
		PRINT*,'BIOLOGICAL TIME=',TIME_BIO
		PRINT*,N_HET,N_AOB,N_NOB,N_EPS,N_INERT
		PRINT*,N_COLONY_AOB,N_COLONY_NOB
        PRINT*,'DISSOLVED EPS',N_EPS_DISSOLVED
		PRINT*,'=========================='
		
		IF (MASS_TRANSFER==1) THEN
        
		CALL SUBSTRATE_UPDATE()    !UPTADE SUBSTRATE FIELD
        END IF
	!	PRINT*,'TEST300'

	!	PRINT*,BAC_N
	!	PAUSE
   
   !========OUTPUT==================

		F_HET=DFLOAT(N_HET)/(N_HET+N_AOB+N_NOB+N_EPS+N_INERT)
		F_AOB=DFLOAT(N_AOB)/(N_HET+N_AOB+N_NOB+N_EPS+N_INERT)
		F_NOB=DFLOAT(N_NOB)/(N_HET+N_AOB+N_NOB+N_EPS+N_INERT)
		F_EPS=DFLOAT(N_EPS)/(N_HET+N_AOB+N_NOB+N_EPS+N_INERT)
		F_INERT=DFLOAT(N_INERT)/(N_HET+N_AOB+N_NOB+N_EPS+N_INERT)


	!	WRITE(10,'(F3.2,5F5.2)'),TIME_BIO,F_HET,F_AOB,F_NOB,F_EPS,F_INERT
        WRITE(10,*),TIME_BIO
		WRITE(11,*),TIME_BIO,FLOC_RADIUS*2
		WRITE(12,*),TIME_BIO,NFLOCS
		WRITE(13,*),TIME_BIO,N_COLONY_AOB,N_COLONY_NOB
        
        WRITE(100,*),F_HET
        WRITE(101,*),F_AOB
        WRITE(102,*),F_NOB
        WRITE(103,*),F_EPS
        WRITE(104,*),F_INERT
        WRITE(105,*),N_HET+N_AOB+N_NOB+N_EPS+N_INERT
        
        WRITE(301,*),DX*DY*DZ*SUM(S_S)
        WRITE(302,*),DX*DY*DZ*SUM(S_O2)
        WRITE(303,*),DX*DY*DZ*SUM(S_NO2)
        WRITE(304,*),DX*DY*DZ*SUM(S_NO3)
        WRITE(305,*),DX*DY*DZ*SUM(S_NH4)
        
    !   J=ITER_GROWTH
       COUNT1=0
       COUNT2=0
       COUNT3=0
       COUNT4=0
       COUNT5=0
   !    PRINT*,'############',BAC_N,BAC_N_PREVIOUS
   !    PAUSE
       DO I=1,BAC_N
     !       IF (I>BAC_N_PREVIOUS) GOTO 10
            
            IF (BAC_S(I)==1 .OR. BAC_DEAD(I)==1) THEN
               COUNT1=COUNT1+1
          !     PRINT*,COUNT,I
          !     PAUSE
                STORE_DATA1(COUNT1)=STORE_DATA1(COUNT1)+DT_BIO*BAC_RATE(I,1)  !HET-S
                STORE_DATA2(COUNT1)=STORE_DATA2(COUNT1)+DT_BIO*BAC_RATE(I,2)  !HET-O2
                STORE_DATA3(COUNT1)=STORE_DATA3(COUNT1)+DT_BIO*BAC_RATE(I,4) !HET-NO2
                STORE_DATA4(COUNT1)=STORE_DATA4(COUNT1)+DT_BIO*BAC_RATE(I,5)  !HET-NO3
                
             
!                PAUSE
        !        PRINT*,'@@@@@@@@@',BAC_RATE(:,2)
            END IF
            IF (BAC_S(I)==2 .OR. BAC_DEAD(I)==2) THEN
               COUNT2=COUNT2+1
          !     PRINT*,COUNT,I
          !     PAUSE
                STORE_DATA5(COUNT2)=STORE_DATA5(COUNT2)+DT_BIO*BAC_RATE(I,2)  !AOB-O2
                STORE_DATA6(COUNT2)=STORE_DATA6(COUNT2)+DT_BIO*BAC_RATE(I,3)  !AOB-NH4
                STORE_DATA7(COUNT2)=STORE_DATA7(COUNT2)+DT_BIO*BAC_RATE(I,4)  !AOB-NO2
     !           STORE_DATA4(COUNT)=STORE_DATA4(COUNT)+DT_BIO*BAC_RATE(I,5)  
                
             
!                PAUSE
        !        PRINT*,'@@@@@@@@@',BAC_RATE(:,2)
            END IF
            
             IF (BAC_S(I)==3 .OR. BAC_DEAD(I)==3) THEN
               COUNT3=COUNT3+1
          !     PRINT*,COUNT,I
          !     PAUSE
                STORE_DATA8(COUNT3)=STORE_DATA8(COUNT3)+DT_BIO*BAC_RATE(I,2) !NOB-O2
                STORE_DATA9(COUNT3)=STORE_DATA9(COUNT3)+DT_BIO*BAC_RATE(I,4)  !NOB-NO2
                STORE_DATA10(COUNT3)=STORE_DATA10(COUNT3)+DT_BIO*BAC_RATE(I,5)  !NOB-NO3
     !           STORE_DATA4(COUNT)=STORE_DATA4(COUNT)+DT_BIO*BAC_RATE(I,5)  
                
             
!                PAUSE
        !        PRINT*,'@@@@@@@@@',BAC_RATE(:,2)
             END IF
             
             IF (BAC_S(I)==4 ) THEN
                 COUNT4=COUNT4+1
                 STORE_DATA11(COUNT4)=STORE_DATA11(COUNT4)+DT_BIO*BAC_RATE(I,1) !EPS-S
             END IF
             
             IF (BAC_DEAD(I)==1 .OR. BAC_DEAD(I)==2 .OR. BAC_DEAD(I)==3 ) THEN
                 COUNT5=COUNT5+1
                 STORE_DATA12(1)=STORE_DATA12(1)+DT_BIO*BAC_RATE(I,1) !DEAD CELL-S
             END IF
            
            
        END DO
10      CONTINUE       
        WRITE(401,"(3000F10.6)"),STORE_DATA1(1:3000)/MASS_HET
        WRITE(402,"(3000F10.6)"),STORE_DATA2(1:3000)/MASS_HET
        WRITE(403,"(3000F10.6)"),STORE_DATA3(1:3000)/MASS_HET
        WRITE(404,"(3000F10.6)"),STORE_DATA4(1:3000)/MASS_HET 
         
        WRITE(405,"(600F10.6)"),STORE_DATA5(1:600)/MASS_HET
        WRITE(406,"(600F10.6)"),STORE_DATA6(1:600)/MASS_HET
        WRITE(407,"(600F10.6)"),STORE_DATA7(1:600)/MASS_HET
        
        WRITE(408,"(600F10.6)"),STORE_DATA8(1:600)/MASS_HET
        WRITE(409,"(600F10.6)"),STORE_DATA9(1:600)/MASS_HET
        WRITE(410,"(600F10.6)"),STORE_DATA10(1:600)/MASS_HET
        
        WRITE(411,"(600F10.6)"),STORE_DATA11(1:600)/MASS_HET
        WRITE(412,"(600F10.6)"),STORE_DATA12(1:600)/MASS_HET
         
	!		WRITE(30,*),'	Zone T = "Sequence ',ITE,'" '

	!IF (ITER_GROWTH==N_GROWTH) THEN
        
        WRITE(4,'(A1,F6.3)'),'*', TIME_BIO
        
	
        
        DO I=1,1000

			IF (I<=BAC_N) THEN
			J=I
			ELSE
				J=1
			END IF

		
		
			WRITE(4,'(3F6.1)'),BAC_X(J)*1.D6,BAC_Y(J)*1.D6,BAC_Z(J)*1.D6

		END DO
		
		
		IF (ITER_GROWTH==N_GROWTH) THEN
		
	!	WRITE(4,'(A1,F6.3)'),'*', TIME_BIO
	
			WRITE(5,*),'<particleset> * ',TIME_BIO
		!	WRITE(5,*),'<particle>'
			
		!	WRITE(5,*),'<sphere>'
		!	WRITE(5,*),'<radius>',BAC_R(1)*1.D6
		!	WRITE(5,*),'</radius>'
		!	WRITE(5,*),'</sphere>'

		
		DO I=1,1000
			IF (I<=BAC_N) THEN
			J=I
			ELSE
				J=1
			END IF
			

		!	WRITE(4,'(3F6.1)'),BAC_X(J)*1.D6,BAC_Y(J)*1.D6,BAC_Z(J)*1.D6

			SELECT CASE (BAC_S(J))

				CASE (1)
					
					WRITE(5,*),'<particle r="0" g="1" b="0" quality="2">'

				CASE (2)
					
					WRITE(5,*),'<particle r="0" g="0" b="1" quality="2">'

				CASE (3)
					
					WRITE(5,*),'<particle r="1" g="0" b="0" quality="2">'
				CASE (4)
					
					WRITE(5,*),'<particle r="0.7" g="0.7" b="0.7" quality="2">'

				CASE (5)
					
					WRITE(5,*),'<particle r="0" g="0" b="0" quality="2">'

				END SELECT


			WRITE(5,*),'<sphere >'
			WRITE(5,*),'<radius>',BAC_R(J)*1.D6
			WRITE(5,*),'</radius>'
			WRITE(5,*),'</sphere>'
			WRITE(5,*),'</particle>'






			
		END DO

		
		WRITE(5,*),'</particleset>'

		END IF


	!	PRINT*,'TEST400'
   !================================
    CALL BIOMASS_ON_GRID()
  
    CALL DIF_COEF()  !UPDATE DIFFUSIVITY FIELDS
   
   
    CALL CPU_TIME(TIME_END)
    
    

   WRITE(14,*),TIME_BIO,TIME_END-TIME_BEGIN
   !CALL OUT(IFRAME)
   
   !==============COMPARISON FOR BIOMASS CALCULATED BY CONTINUOUS AND Ib MODELS
   CALL CONTINUOUS_MODEL(ITER_GROWTH,C_MASS_HET,C_MASS_AOB,C_MASS_NOB,C_MASS_HET_EPS,C_MASS_PAR_EPS,C_MASS_INERT)
   I_MASS_HET=DX*DY*DZ*SUM(X_HET)
   I_MASS_AOB=DX*DY*DZ*SUM(X_AOB)
   I_MASS_NOB=DX*DY*DZ*SUM(X_NOB)
   I_MASS_PAR_EPS=DX*DY*DZ*SUM(X_EPS)
   I_MASS_INERT=DX*DY*DZ*SUM(X_I)
   
   
   
   PRINT*,'=======BIOMASS-CONTINUOUS & Ib MODELS================'
  ! PRINT*,'C_MASS_AOB=',C_MASS_NOB
  ! PRINT*,'I_MASS_AOB=',I_MASS_NOB
   
   WRITE(15,*),DABS(C_MASS_HET-I_MASS_HET)/C_MASS_HET,DABS(C_MASS_AOB-I_MASS_AOB)/C_MASS_AOB,DABS(C_MASS_NOB-I_MASS_NOB)/C_MASS_NOB,DABS(C_MASS_PAR_EPS-I_MASS_PAR_EPS)/C_MASS_PAR_EPS,DABS(C_MASS_INERT-I_MASS_INERT)/C_MASS_INERT
   
   WRITE(201,*),I_MASS_AOB
   WRITE(202,*),C_MASS_AOB
   
   WRITE(203,*),I_MASS_HET
   WRITE(204,*),C_MASS_HET
   
    WRITE(205,*),I_MASS_NOB
     WRITE(206,*),C_MASS_NOB
     
     WRITE(207,*),I_MASS_PAR_EPS
     WRITE(208,*),I_MASS_INERT
   
    END DO
    
    
    
    
    IF (MASS_TRANSFER==1) THEN
	TIME_PHY=0.D0	
   DO WHILE (TIME_PHY<TOTAL_TIME_PHY)
		
		CALL MASS_TRANSPORT_SOLVER(S_RESIDUAL)	
	
		TIME_PHY=TIME_PHY+DT_PHY
		PRINT*,'PHYSICAL TIME=',TIME_PHY,S_RESIDUAL
		!	PRINT*,S_O2(MX/2,MY/2,2),S_O2(MX/2,MY/2,MZ-1)
        IF (S_RESIDUAL<10.D-6) TIME_PHY=TOTAL_TIME_PHY
	END DO
    END IF

   
  ! DO K=1,MZ
   !    WRITE(1,*),K,S_O2(MX/2,MY/2,K)
       
   !END DO
   ! DO K=1,MZ
  !     WRITE(1,*),K,S_O2(MX/4,MY/2,K)
       
  ! END DO
  ! DO K=1,MZ
    !   WRITE(1,*),K,S_O2(2,MY/2,K)
       
  ! END DO
    
  !  DO K=1,MZ
    !    DO J=1,MY
    !        DO I=1,MX
    !            WRITE(2,*),I,J,K,S_O2(I,J,K)
    !        END DO
   !     END DO
   ! END DO
    
    WRITE(2,'(A26)'),'# vtk DataFile Version 3.0'
    WRITE(2,'(A10)'),'vtk output'
    WRITE(2,'(A5)'),'ASCII'
    WRITE(2,'(A24)'),'DATASET RECTILINEAR_GRID'
    WRITE(2,'(A19)'),'DIMENSIONS 20 20 20'
!	WRITE(2,*),'DIMENSIONS',MX,MY,MZ,'
    WRITE(2,'(A22)'),'X_COORDINATES 20 float'
	WRITE(2,'(A49)'),'0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19'
	
    WRITE(2,'(A22)'),'Y_COORDINATES 20 float'
    WRITE(2,'(A49)'),'0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19'
    WRITE(2,'(A22)'),'Z_COORDINATES 20 float'
    WRITE(2,'(A49)'),'0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19'
   ! WRITE(2,'(A11)'),'CELL_DATA 81'
    WRITE(2,'(A15)'),'POINT_DATA 8000'
    !WRITE(2,'(A17)'),'FIELD FieldData 1'
    !WRITE(2,'(A15)'),'nodal 1 4 float'
    WRITE(2,'(A31)'),'SCALARS scalar_variable float 1'
    WRITE(2,'(A20)'),'LOOKUP_TABLE default'
   ! DO I=1,32
    !WRITE(2,'(I9)'),-10
    
   ! END DO

	WRITE(3,'(A26)'),'# vtk DataFile Version 3.0'
	WRITE(3,'(A25)'),'Unstructured Grid Example'
	WRITE(3,'(A5)'),'ASCII'
	WRITE(3,'(A24)'),'DATASET UNSTRUCTURED_GRID'
	WRITE(3,'(A6,I3,A6)'),'POINTS', BAC_N, 'float'
  
!	DO I=1,3
!		WRITE(3,'(3I2)'),I,I,I
!	END DO

	DO I=1,BAC_N
		WRITE(3,'(3F8.4)'),BAC_X(I)*1.D4,BAC_Y(I)*1.D4,BAC_Z(I)*1.D4
	END DO
  
   
    DO K=1,MZ
        DO J=1,MY
            DO I=1,MX
                WRITE(2,*),S_NO3(I,J,K)
	!			WRITE(2,*),X_AOB(I,J,K)
	!			PRINT*,D_O2(I,J,K)
				WRITE(1,*),BIOMASS_OCCUPANCY(I,J,K)
            END DO
        END DO
    END DO


	
	
	


	

PRINT*,'SUMMARY OF PARTCILES'
PRINT*,'HET=',N_HET
PRINT*,'AOB=',N_AOB
PRINT*,'NOB=',N_NOB
PRINT*,'EPS=',N_EPS
PRINT*,'INERT=',N_INERT
PRINT*,'TOTAL=',N_HET+N_AOB+N_NOB+N_EPS+N_INERT

!PRINT*,STORE_DATA
    
    
    PAUSE

    END PROGRAM MAIN

!===============================================================================
!DEFINE GLOBAL VARIABLES



    
    
    
    

