# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   
PKG_PATH =  -L../../lib/nufeb 
PKG_LIB =   
PKG_CPP_DEPENDS = 
PKG_LINK_DEPENDS = 

PKG_SYSINC =  $(nufeb_SYSINC) 
PKG_SYSLIB =  $(nufeb_SYSLIB) 
PKG_SYSPATH = $(nufeb_SYSPATH) 
