FROM ubuntu:16.04

#add new user
RUN useradd --create-home --shell /bin/bash admin

#install required libs
RUN apt-get update
RUN apt-get -y install build-essential sudo make git openmpi-bin openmpi-common libopenmpi-dev libvtk6-dev vim 

#switch to user admin, download NUFEB
USER admin
#WORKDIR /home/admin
#RUN git clone https://nufebdocker:nufeb123@github.com/shelllbw/nufeb.git
#WORKDIR /home/admin/nufeb

#setup vtk makefile
#WORKDIR /home/admin/nufeb/code/lammps5Nov16/lib/vtk
#RUN cp Makefile.lammps.ubuntu16.04_vtk6.2 Makefile.lammps
#WORKDIR /home/admin/nufeb/code/lammps5Nov16/lib/nufeb
#RUN cp Makefile.lammps.ubuntu16.04_vtk6.2.dump_grid Makefile.lammps

#compile NUFEB code
#WORKDIR /home/admin/nufeb/code/lammps5Nov16/src
#RUN make yes-user-nufeb
#RUN make yes-granular
#RUN make yes-user-vtk
#RUN make -j4 mpi

#add NUFEB executable to bashrc
#RUN echo "export PATH=$PATH:/home/admin/nufeb/code/lammps5Nov16/src/" >> /home/admin/.bashrc

#install nufebfoam 
#OpenFOAM240 downloading and installation
RUN cd ~
RUN mkdir OpenFOAM
RUN cd OpenFOAM
RUN wget "http://downloads.sourceforge.net/foam/OpenFOAM-2.4.0.tgz?use_mirror=mesh" -O OpenFOAM-2.4.0.tgz
RUN wget "http://downloads.sourceforge.net/foam/ThirdParty-2.4.0.tgz?use_mirror=mesh" -O ThirdParty-2.4.0.tgz
 
RUN tar -xzf OpenFOAM-2.4.0.tgz 
RUN tar -xzf ThirdParty-2.4.0.tgz

#make a few symbolic links that should ensure that the correct global MPI installation is used by this OpenFOAM installation: 

RUN ln -s /usr/bin/mpicc.openmpi OpenFOAM-2.4.0/bin/mpicc
RUN ln -s /usr/bin/mpirun.openmpi OpenFOAM-2.4.0/bin/mpirun

RUN source $HOME/OpenFOAM/OpenFOAM-2.4.0/etc/bashrc WM_NCOMPPROCS=4
RUN echo "alias of240='source \$HOME/OpenFOAM/OpenFOAM-2.4.0/etc/bashrc $FOAM_SETTINGS'" >> $HOME/.bashrc
RUN RUN echo "of240" >> /home/admin/.bashrc

#before we can build OpenFOAM, we need to do a few fixes
RUN cd $WM_PROJECT_DIR
RUN find src applications -name "*.L" -type f | xargs sed -i -e 's=\(YY\_FLEX\_SUBMINOR\_VERSION\)=YY_FLEX_MINOR_VERSION < 6 \&\& \1='

RUN mkdir -p $CGAL_ARCH_PATH
RUN mkdir -p $BOOST_ARCH_PATH

RUN cd $WM_PROJECT_DIR
RUN export QT_SELECT=qt4
RUN ./Allwmake > log.make 2>&1
